"""AI Code Engine — generates playable game source code with modular templates.

Supports multiple genres with realistic AI, physics, and narrative.
"""

from __future__ import annotations
from typing import Any, Optional
from pathlib import Path
import math

from nicto_game.core.config import GameConfig, GameGenre, RenderMode
from nicto_game.core.types import GameMap, TileType


class CodeEngine:
    """Generates complete game source code from config and world data."""

    def __init__(self):
        self._generated_count = 0

    async def generate(self, config: GameConfig, game_map: GameMap,
                       characters: list | None = None,
                       quests: list | None = None,
                       audio_assets: dict | None = None) -> str:
        self._generated_count += 1
        audio_code = self._generate_audio_code(audio_assets)

        w, h = game_map.width, game_map.height
        map_str = self._map_to_str(game_map.tiles)
        enemy_positions = []
        for k, v in game_map.spawn_points.items():
            if k.startswith("enemy_"):
                enemy_positions.append(v)

        player_start = game_map.spawn_points.get("player", (1, 1))
        items = []
        for k, v in game_map.spawn_points.items():
            if k.startswith("item_"):
                items.append(v)

        npcs = []
        if characters:
            for i, ch in enumerate(characters):
                pos = game_map.spawn_points.get(f"npc_{i}", (w // 2, h // 2))
                npcs.append({"name": getattr(ch, 'name', f'NPC_{i}'),
                             "x": pos[0], "y": pos[1],
                             "dialog": getattr(ch, 'dialog', ["Hello!"])})

        code = self._render_template(
            config=config,
            map_str=map_str,
            map_w=w, map_h=h,
            player_x=player_start[0], player_y=player_start[1],
            enemies=enemy_positions,
            items=items,
            npcs=npcs or None,
            audio_code=audio_code,
            has_quests=bool(quests),
        )
        return code

    def _render_template(self, **kw) -> str:
        c = kw["config"]
        genre_key = c.genre.value
        if genre_key in ("fps", "shooter", "maze"):
            return self._template_fps(**kw)
        elif genre_key in ("platformer", "platform"):
            return self._template_platformer(**kw)
        elif genre_key in ("rpg", "adventure", "dungeon"):
            return self._template_rpg(**kw)
        elif genre_key in ("survival", "horror"):
            return self._template_survival(**kw)
        elif genre_key in ("roguelike", "rogue"):
            return self._template_roguelike(**kw)
        else:
            return self._template_fps(**kw)

    def _template_fps(self, **kw) -> str:
        c = kw["config"]
        gm, h = kw["map_w"], kw["map_h"]
        enemy_count = len(kw["enemies"])
        npcs = kw.get("npcs")
        npc_count = len(npcs) if npcs else 0

        return f'''"""
{c.name} — generated by NICTO Omega Game Engine
Genre: {c.genre.value} | AI State Machine | Enhanced Physics
{c.description}
"""

import math, random, sys, pygame
from pygame.locals import *

# === CONFIG ===
WIN_W, WIN_H = {c.graphics.resolution_width}, {c.graphics.resolution_height}
FOV = {c.graphics.fov}
PLAYER_SPEED = {c.gameplay.speed}
PLAYER_HEALTH = {c.gameplay.health}
GRAVITY = {c.gameplay.gravity}
MAP_W, MAP_H = {gm}, {h}
MOUSE_SENS = 0.003
ENEMY_COUNT = {enemy_count}
NPC_COUNT = {npc_count}

# === MAP ===
MAP = {kw["map_str"]}

TILE_WALL, TILE_EMPTY, TILE_WATER, TILE_DOOR = 1, 0, 2, 4
TILE_ENEMY, TILE_ITEM, TILE_EXIT, TILE_NPC = 5, 6, 7, 8
WALKABLE = {{0, 4, 6, 7, 8}}

# === COLOR PALETTE ===
COLORS = {{
    0: (40,40,40), 1: (120,100,80), 2: (20,60,120), 3: (20,80,30),
    4: (140,100,50), 5: (200,30,30), 6: (200,200,30), 7: (30,200,30),
    8: (30,30,200),
}}

# === ENEMY AI STATE MACHINE ===
AI_IDLE, AI_PATROL, AI_ALERT, AI_CHASE, AI_ATTACK, AI_FLEE, AI_SEARCH = range(7)

class EnemyAI:
    def __init__(self, x, y, hp=100):
        self.x = x; self.y = y; self.hp = hp; self.max_hp = hp
        self.state = AI_PATROL if random.random() < 0.7 else AI_IDLE
        self.speed = 1.2 + random.uniform(-0.3, 0.3)
        self.damage = 8 + random.randint(-2, 4)
        self.alert_timer = 0.0
        self.search_timer = 0.0
        self.attack_cooldown = 0.0
        self.patrol_target = (x, y)
        self.last_known_player = None
        self.detection_range = 8 + random.uniform(-1, 2)
        self.attack_range = 1.2

    def update(self, dt, px, py, walkable_fn):
        ddx = px - self.x
        ddy = py - self.y
        dist = math.hypot(ddx, ddy)
        self.alert_timer = max(0, self.alert_timer - dt)
        self.attack_cooldown = max(0, self.attack_cooldown - dt)
        self.search_timer = max(0, self.search_timer - dt)

        if self.state == AI_IDLE:
            if dist < self.detection_range:
                self.state = AI_ALERT
                self.alert_timer = 0.5
                self.last_known_player = (px, py)

        elif self.state == AI_PATROL:
            if dist < self.detection_range:
                self.state = AI_ALERT
                self.alert_timer = 0.5
                self.last_known_player = (px, py)
            else:
                tx, ty = self.patrol_target
                dx, dy = tx - self.x, ty - self.y
                pd = math.hypot(dx, dy)
                if pd < 0.5:
                    self.patrol_target = (random.randint(1, MAP_W-2), random.randint(1, MAP_H-2))
                elif pd > 0:
                    nx = self.x + (dx/pd) * self.speed * 0.4 * dt
                    ny = self.y + (dy/pd) * self.speed * 0.4 * dt
                    if walkable_fn(nx, self.y): self.x = nx
                    if walkable_fn(self.x, ny): self.y = ny

        elif self.state == AI_ALERT:
            self.alert_timer -= dt
            if self.alert_timer <= 0:
                self.state = AI_CHASE
                self.last_known_player = (px, py)

        elif self.state == AI_CHASE:
            if dist < self.attack_range:
                self.state = AI_ATTACK
            elif dist < self.detection_range * 2:
                if dist > 0:
                    nx = self.x + (ddx/dist) * self.speed * dt
                    ny = self.y + (ddy/dist) * self.speed * dt
                    if walkable_fn(nx, self.y): self.x = nx
                    if walkable_fn(self.x, ny): self.y = ny
                self.last_known_player = (px, py)
            else:
                self.state = AI_SEARCH
                self.search_timer = 3.0

        elif self.state == AI_ATTACK:
            if dist > self.attack_range * 1.5:
                self.state = AI_CHASE
            elif self.attack_cooldown <= 0:
                self.attack_cooldown = 1.0
                return "attack", self.damage
            if dist > 0:
                nx = self.x + (ddx/dist) * self.speed * 0.3 * dt
                ny = self.y + (ddy/dist) * self.speed * 0.3 * dt
                if walkable_fn(nx, self.y): self.x = nx
                if walkable_fn(self.x, ny): self.y = ny

        elif self.state == AI_FLEE:
            hp_ratio = self.hp / self.max_hp
            if hp_ratio > 0.3 and dist < self.detection_range:
                self.state = AI_CHASE
            elif dist > 0:
                nx = self.x + (-ddx/dist) * self.speed * 1.2 * dt
                ny = self.y + (-ddy/dist) * self.speed * 1.2 * dt
                if walkable_fn(nx, self.y): self.x = nx
                if walkable_fn(self.x, ny): self.y = ny

        elif self.state == AI_SEARCH:
            if self.last_known_player:
                lx, ly = self.last_known_player
                dx, dy = lx - self.x, ly - self.y
                pd = math.hypot(dx, dy)
                if pd < 1.0 or self.search_timer <= 0:
                    self.state = AI_PATROL
                    self.last_known_player = None
                elif pd > 0:
                    nx = self.x + (dx/pd) * self.speed * 0.6 * dt
                    ny = self.y + (dy/pd) * self.speed * 0.6 * dt
                    if walkable_fn(nx, self.y): self.x = nx
                    if walkable_fn(self.x, ny): self.y = ny

        if self.hp <= 0:
            return "death", 0
        return None, 0

# === PHYSICS ===
def point_in_rect(px, py, rx, ry, rw, rh):
    return rx <= px <= rx + rw and ry <= py <= ry + rh

def line_intersects_rect(x1, y1, x2, y2, rx, ry, rw, rh):
    steps = int(math.hypot(x2-x1, y2-y1) / 0.5) + 1
    for i in range(steps):
        t = i / max(steps, 1)
        px = x1 + (x2 - x1) * t
        py = y1 + (y2 - y1) * t
        if point_in_rect(px, py, rx, ry, rw, rh):
            return True
    return False

class Projectile:
    def __init__(self, x, y, angle, speed=6.0, damage=25):
        self.x = x; self.y = y
        self.dx = math.cos(angle) * speed
        self.dy = math.sin(angle) * speed
        self.damage = damage
        self.life = 2.0

    def update(self, dt, walkable_fn):
        self.x += self.dx * dt
        self.y += self.dy * dt
        self.life -= dt
        if not walkable_fn(self.x, self.y):
            return "hit_wall"
        return None

# === GAME CLASS ===
class Game:
    def __init__(self):
        pygame.init()
        flags = pygame.DOUBLEBUF | pygame.HWSURFACE
        self.screen = pygame.display.set_mode((WIN_W, WIN_H), flags)
        pygame.display.set_caption("{c.name}")
        self.clock = pygame.time.Clock()
        self.running = True
        self.px, self.py = {kw["player_x"]}.0, {kw["player_y"]}.0
        self.pa = 0.0
        self.hp = PLAYER_HEALTH
        self.max_hp = PLAYER_HEALTH
        self.score = 0
        self.keys = 0
        self.game_over = False
        self.victory = False
        self.font = pygame.font.SysFont("Arial", 16)
        self.big_font = pygame.font.SysFont("Arial", 48)

        self.enemies = [EnemyAI(ex+0.5, ey+0.5) for ex, ey in {kw["enemies"]}]
        self.projectiles = []
        self.items = []
        for ix, iy in {kw["items"]}:
            self.items.append([ix+0.5, iy+0.5, random.choice(["health", "key", "score", "weapon"])])
        self.ammo = 30
        self.last_shot = 0
        self.shoot_cooldown = 300
        self.knockback_x, self.knockback_y = 0.0, 0.0

    def is_walkable(self, x, y):
        mx, my = int(x), int(y)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H:
            return MAP[my][mx] in WALKABLE
        return False

    def handle_events(self):
        for event in pygame.event.get():
            if event.type == QUIT: self.running = False
            if event.type == KEYDOWN:
                if event.key == K_ESCAPE: self.running = False

    def update(self, dt):
        if self.game_over or self.victory: return
        keys = pygame.key.get_pressed()
        dx, dy = 0.0, 0.0
        forward = (keys[K_w] or keys[K_UP]) - (keys[K_s] or keys[K_DOWN])
        strafe = (keys[K_d] and not keys[K_a]) - (keys[K_a] and not keys[K_d])
        if forward:
            dx += math.cos(self.pa) * forward * PLAYER_SPEED * dt
            dy += math.sin(self.pa) * forward * PLAYER_SPEED * dt
        if strafe:
            dx += math.cos(self.pa + math.pi/2) * strafe * PLAYER_SPEED * 0.7 * dt
            dy += math.sin(self.pa + math.pi/2) * strafe * PLAYER_SPEED * 0.7 * dt
        if keys[K_LEFT]: self.pa -= 2.5 * dt
        if keys[K_RIGHT]: self.pa += 2.5 * dt
        if keys[K_SPACE] or keys[K_LCTRL]:
            now = pygame.time.get_ticks()
            if now - self.last_shot > self.shoot_cooldown and self.ammo > 0:
                self.ammo -= 1
                self.projectiles.append(Projectile(self.px, self.py, self.pa))
                self.last_shot = now

        mx, my = pygame.mouse.get_rel()
        self.pa += mx * MOUSE_SENS

        if self.is_walkable(self.px + dx, self.py): self.px += dx
        if self.is_walkable(self.px, self.py + dy): self.py += dy

        for p in self.projectiles[:]:
            result = p.update(dt, self.is_walkable)
            if result == "hit_wall":
                self.projectiles.remove(p)
                continue
            for e in self.enemies[:]:
                if math.hypot(p.x - e.x, p.y - e.y) < 0.6:
                    e.hp -= p.damage
                    self.projectiles.remove(p)
                    if e.hp <= 0:
                        self.enemies.remove(e)
                        self.score += 100
                    break

        for e in self.enemies[:]:
            result, dmg = e.update(dt, self.px, self.py, self.is_walkable)
            if result == "attack":
                self.hp -= dmg
                angle = math.atan2(self.py - e.y, self.px - e.x)
                self.knockback_x = math.cos(angle) * 3
                self.knockback_y = math.sin(angle) * 3
            if result == "death":
                self.enemies.remove(e)
                self.score += 100

        if self.knockback_x != 0 or self.knockback_y != 0:
            kbx = self.knockback_x * dt * 10
            kby = self.knockback_y * dt * 10
            if self.is_walkable(self.px + kbx, self.py): self.px += kbx
            if self.is_walkable(self.px, self.py + kby): self.py += kby
            self.knockback_x *= 0.9
            self.knockback_y *= 0.9

        for item in self.items[:]:
            if math.hypot(item[0]-self.px, item[1]-self.py) < 0.6:
                if item[2] == "health": self.hp = min(self.max_hp, self.hp+25)
                elif item[2] == "key": self.keys += 1
                elif item[2] == "score": self.score += 50
                elif item[2] == "weapon": self.ammo += 15
                self.items.remove(item)

        if self.hp <= 0: self.hp = 0; self.game_over = True
        mx, my = int(self.px), int(self.py)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H and MAP[my][mx] == TILE_EXIT:
            self.victory = True

    def render(self):
        if self.game_over or self.victory:
            self.screen.fill((10,10,10))
            text = "GAME OVER" if self.game_over else "VICTORY!"
            color = (200,50,50) if self.game_over else (50,200,50)
            surf = self.big_font.render(text, True, color)
            self.screen.blit(surf, (WIN_W//2-surf.get_width()//2, WIN_H//2-50))
            surf2 = self.font.render("Press ESC to exit", True, (200,200,200))
            self.screen.blit(surf2, (WIN_W//2-surf2.get_width()//2, WIN_H//2+10))
            pygame.display.flip(); return

        self.render_raycast()
        self.render_hud()
        self.render_minimap()
        pygame.display.flip()

    def render_raycast(self):
        for x in range(WIN_W):
            ray_angle = self.pa - FOV/2 + (x/WIN_W)*FOV
            sin_a, cos_a = math.sin(ray_angle), math.cos(ray_angle)
            dist = 0.0; hit = False
            while not hit and dist < 20:
                dist += 0.05
                tx = int(self.px + cos_a * dist)
                ty = int(self.py + sin_a * dist)
                if 0 <= tx < MAP_W and 0 <= ty < MAP_H:
                    if MAP[ty][tx] == TILE_WALL: hit = True
                    elif MAP[ty][tx] == TILE_DOOR and dist > 0.5: hit = True
                else: hit = True; dist = 20
            dist *= math.cos(ray_angle - self.pa)
            wall_h = int(WIN_H / max(dist, 0.1))
            shade = max(30, min(255, 255 - dist*12))
            wall_color = (shade, shade*2//3, shade//2)
            pygame.draw.line(self.screen, (shade//4,shade//4,shade//2), (x,0), (x,WIN_H//2-wall_h//2))
            pygame.draw.line(self.screen, wall_color, (x,WIN_H//2-wall_h//2), (x,WIN_H//2+wall_h//2))
            pygame.draw.line(self.screen, (shade//3,shade//3,shade//3), (x,WIN_H//2+wall_h//2), (x,WIN_H))
        cx, cy = WIN_W//2, WIN_H//2
        pygame.draw.line(self.screen, (0,255,0), (cx-8,cy), (cx+8,cy), 2)
        pygame.draw.line(self.screen, (0,255,0), (cx,cy-8), (cx,cy+8), 2)

    def render_hud(self):
        hp_c = (0,255,0) if self.hp>50 else (255,255,0) if self.hp>25 else (255,0,0)
        texts = [f"HP: {{int(self.hp)}}", f"SCORE: {{self.score}}",
                 f"ENEMIES: {{len(self.enemies)}}", f"AMMO: {{self.ammo}}"]
        for i,t in enumerate(texts):
            self.screen.blit(self.font.render(t, True, (200,200,200)), (10,10+i*20))
        pygame.draw.rect(self.screen, (60,60,60), (10,100,150,12))
        pygame.draw.rect(self.screen, hp_c, (10,100,int((self.hp/self.max_hp)*150),12))

    def render_minimap(self):
        ms = 120; mt = max(1, ms//max(MAP_W,MAP_H))
        mx, my = WIN_W-ms-10, 10
        for yy in range(MAP_H):
            for xx in range(MAP_W):
                pygame.draw.rect(self.screen, COLORS.get(MAP[yy][xx],(0,0,0)), (mx+xx*mt, my+yy*mt, mt, mt))
        pygame.draw.circle(self.screen, (0,255,0), (mx+int(self.px*mt), my+int(self.py*mt)), 3)

    def run(self):
        while self.running:
            dt = self.clock.tick(60) / 1000.0
            self.handle_events()
            self.update(dt)
            self.render()
        pygame.quit()

if __name__ == "__main__":
    Game().run()
'''

    def _template_platformer(self, **kw) -> str:
        c = kw["config"]
        gm, h = kw["map_w"], kw["map_h"]

        return f'''"""
{c.name} — NICTO Platformer with Enhanced Physics
"""

import math, random, sys, pygame
from pygame.locals import *

WIN_W, WIN_H = {c.graphics.resolution_width}, {c.graphics.resolution_height}
MAP_W, MAP_H = {gm}, {h}
GRAVITY = {c.gameplay.gravity}
PLAYER_SPEED = {c.gameplay.speed}
PLAYER_JUMP = -12.0
PLAYER_HEALTH = {c.gameplay.health}

MAP = {kw["map_str"]}
WALKABLE = {{0, 4, 6, 7, 8}}
COLORS = {{0:(50,50,60),1:(140,110,90),2:(30,70,140),3:(40,120,50),
           4:(130,100,50),5:(200,40,40),6:(200,200,40),7:(40,200,40),8:(40,40,200)}}

class Player:
    def __init__(self, x, y):
        self.x, self.y = float(x), float(y)
        self.vx, self.vy = 0.0, 0.0
        self.w, self.h = 0.6, 0.8
        self.on_ground = False
        self.hp = PLAYER_HEALTH
        self.max_hp = PLAYER_HEALTH
        self.score = 0
        self.facing = 1

    def update(self, dt, keys, map_data):
        accel = PLAYER_SPEED * 8.0
        friction = 5.0
        if keys[K_a] or keys[K_LEFT]:
            self.vx -= accel * dt; self.facing = -1
        if keys[K_d] or keys[K_RIGHT]:
            self.vx += accel * dt; self.facing = 1
        if not (keys[K_a] or keys[K_LEFT] or keys[K_d] or keys[K_RIGHT]):
            self.vx *= max(0, 1 - friction * dt)
        self.vx = max(-PLAYER_SPEED*2, min(PLAYER_SPEED*2, self.vx))

        if (keys[K_w] or keys[K_UP] or keys[K_SPACE]) and self.on_ground:
            self.vy = PLAYER_JUMP
            self.on_ground = False

        self.vy += GRAVITY * dt
        self.vy = min(20.0, self.vy)

        new_x = self.x + self.vx * dt
        new_y = self.y + self.vy * dt

        self.on_ground = False
        if not self._collides(new_x, self.y, map_data):
            self.x = new_x
        else:
            self.vx = 0
        if not self._collides(self.x, new_y, map_data):
            self.y = new_y
        else:
            if self.vy > 0: self.on_ground = True
            self.vy = 0

    def _collides(self, x, y, map_data):
        for yy in range(int(y), int(y+self.h)+1):
            for xx in range(int(x), int(x+self.w)+1):
                if 0 <= xx < MAP_W and 0 <= yy < MAP_H:
                    if map_data[yy][xx] not in WALKABLE:
                        return True
                elif yy < 0: return True
        return False

class Game:
    def __init__(self):
        pygame.init()
        self.screen = pygame.display.set_mode((WIN_W, WIN_H))
        pygame.display.set_caption("{c.name}")
        self.clock = pygame.time.Clock()
        self.running = True
        self.player = Player({kw["player_x"]}, {kw["player_y"]})
        self.camera_x, self.camera_y = 0, 0
        self.collectibles = []
        for ix, iy in {kw["items"]}:
            self.collectibles.append([float(ix)+0.5, float(iy)+0.5])
        self.enemies = []
        for ex, ey in {kw["enemies"]}:
            self.enemies.append([float(ex)+0.5, float(ey)+0.5, 100.0, 0.0])
        self.font = pygame.font.SysFont("Arial", 16)
        self.big_font = pygame.font.SysFont("Arial", 48)
        self.game_over = False; self.victory = False

    def handle_events(self):
        for e in pygame.event.get():
            if e.type == QUIT: self.running = False
            if e.type == KEYDOWN and e.key == K_ESCAPE: self.running = False

    def update(self, dt):
        if self.game_over or self.victory: return
        keys = pygame.key.get_pressed()
        self.player.update(dt, keys, MAP)
        self.camera_x = int(self.player.x * 48 - WIN_W//2)
        self.camera_y = int(self.player.y * 48 - WIN_H//2)

        for c in self.collectibles[:]:
            if math.hypot(c[0]-self.player.x, c[1]-self.player.y) < 0.6:
                self.collectibles.remove(c); self.player.score += 50

        for e in self.enemies[:]:
            dx, dy = self.player.x - e[0], self.player.y - e[1]
            d = math.hypot(dx, dy)
            if d < 0.8:
                self.player.hp -= 5 * dt
                if self.player.hp <= 0:
                    self.player.hp = 0; self.game_over = True
            if d > 0 and d < 10:
                speed = 1.0 * dt
                nx = e[0] + (dx/d) * speed; ny = e[1] + (dy/d) * speed
                e[0] = nx; e[1] = ny

        if self.player.hp <= 0: self.game_over = True
        mx, my = int(self.player.x), int(self.player.y)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H and MAP[my][mx] == 7:
            self.victory = True

    def render(self):
        self.screen.fill((30,30,50))
        if self.game_over or self.victory:
            text = "GAME OVER" if self.game_over else "VICTORY!"
            color = (200,50,50) if self.game_over else (50,200,50)
            surf = self.big_font.render(text, True, color)
            self.screen.blit(surf, (WIN_W//2-surf.get_width()//2, WIN_H//2-50))
            pygame.display.flip(); return

        tile_size = 48
        for y in range(MAP_H):
            for x in range(MAP_W):
                screen_x = x*tile_size - self.camera_x
                screen_y = y*tile_size - self.camera_y
                if -tile_size <= screen_x <= WIN_W + tile_size and -tile_size <= screen_y <= WIN_H + tile_size:
                    pygame.draw.rect(self.screen, COLORS.get(MAP[y][x],(0,0,0)), (screen_x,screen_y,tile_size,tile_size))

        player_color = (0,200,0) if self.player.hp > 30 else (200,200,0)
        px = int(self.player.x*tile_size - self.camera_x)
        py = int(self.player.y*tile_size - self.camera_y)
        pygame.draw.rect(self.screen, player_color, (px,py,int(self.player.w*tile_size),int(self.player.h*tile_size)))
        pygame.draw.circle(self.screen, (255,255,0), (px+12, py-5), 4)

        self.screen.blit(self.font.render(f"HP: {{int(self.player.hp)}}", True, (200,200,200)), (10,10))
        self.screen.blit(self.font.render(f"SCORE: {{self.player.score}}", True, (200,200,200)), (10,30))
        pygame.display.flip()

    def run(self):
        while self.running:
            dt = self.clock.tick(60)/1000.0
            self.handle_events()
            self.update(dt)
            self.render()
        pygame.quit()

if __name__ == "__main__":
    Game().run()
'''

    def _template_rpg(self, **kw) -> str:
        c = kw["config"]
        gm, h = kw["map_w"], kw["map_h"]
        npcs = kw.get("npcs")

        return f'''"""
{c.name} — NICTO Top-Down RPG
"""

import math, random, sys, pygame
from pygame.locals import *

WIN_W, WIN_H = {c.graphics.resolution_width}, {c.graphics.resolution_height}
MAP_W, MAP_H = {gm}, {h}
PLAYER_SPEED = {c.gameplay.speed}
PLAYER_HEALTH = {c.gameplay.health}

MAP = {kw["map_str"]}
WALKABLE = {{0, 4, 6, 7, 8}}
COLORS = {{0:(50,50,60),1:(120,100,80),2:(30,70,140),3:(40,120,50),
           4:(140,100,50),5:(200,40,40),6:(200,200,40),7:(40,200,40),8:(40,40,200)}}

class Game:
    def __init__(self):
        pygame.init()
        self.screen = pygame.display.set_mode((WIN_W, WIN_H))
        pygame.display.set_caption("{c.name}")
        self.clock = pygame.time.Clock()
        self.running = True
        self.px, self.py = float({kw["player_x"]}), float({kw["player_y"]})
        self.hp = PLAYER_HEALTH; self.max_hp = PLAYER_HEALTH
        self.level = 1; self.exp = 0; self.gold = 0
        self.inventory = ["Sword", "Shield"]
        self.dialog_active = False; self.dialog_lines = []; self.dialog_index = 0
        self.font = pygame.font.SysFont("Arial", 16)
        self.big_font = pygame.font.SysFont("Arial", 48)
        self.game_over = False; self.victory = False
        self.camera_x, self.camera_y = 0, 0
        self.tile_size = 48
        self.enemies = []
        for ex, ey in {kw["enemies"]}:
            self.enemies.append([float(ex)+0.5, float(ey)+0.5, 100.0, 0])

    def is_walkable(self, x, y):
        mx, my = int(x), int(y)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H: return MAP[my][mx] in WALKABLE
        return False

    def handle_events(self):
        for e in pygame.event.get():
            if e.type == QUIT: self.running = False
            if e.type == KEYDOWN:
                if e.key == K_ESCAPE: self.running = False
                if e.key == K_RETURN and self.dialog_active:
                    self.dialog_index += 1
                    if self.dialog_index >= len(self.dialog_lines):
                        self.dialog_active = False; self.dialog_lines = []; self.dialog_index = 0

    def update(self, dt):
        if self.game_over or self.victory: return
        keys = pygame.key.get_pressed()
        dx, dy = 0, 0
        if keys[K_w]: dy -= PLAYER_SPEED * dt
        if keys[K_s]: dy += PLAYER_SPEED * dt
        if keys[K_a]: dx -= PLAYER_SPEED * dt
        if keys[K_d]: dx += PLAYER_SPEED * dt
        if dx != 0 and dy != 0: dx *= 0.707; dy *= 0.707

        if self.is_walkable(self.px+dx, self.py): self.px += dx
        if self.is_walkable(self.px, self.py+dy): self.py += dy

        for e in self.enemies[:]:
            if e[2] > 0:
                d = math.hypot(self.px-e[0], self.py-e[1])
                if d < 1.0: self.hp -= 3 * dt
                if d > 0 and d < 6:
                    nx = e[0] + (self.px-e[0])/d * 1.5 * dt
                    ny = e[1] + (self.py-e[1])/d * 1.5 * dt
                    if self.is_walkable(nx, e[1]): e[0] = nx
                    if self.is_walkable(e[0], ny): e[1] = ny
            else:
                self.enemies.remove(e); self.exp += 25
                if self.exp >= self.level * 50:
                    self.exp -= self.level * 50; self.level += 1; self.max_hp += 10; self.hp = self.max_hp

        if self.hp <= 0: self.hp = 0; self.game_over = True
        mx, my = int(self.px), int(self.py)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H and MAP[my][mx] == 7:
            self.victory = True

        self.camera_x = int(self.px*self.tile_size - WIN_W//2)
        self.camera_y = int(self.py*self.tile_size - WIN_H//2)

    def render(self):
        self.screen.fill((20,20,30))
        if self.game_over or self.victory:
            text = "GAME OVER" if self.game_over else "VICTORY!"
            color = (200,50,50) if self.game_over else (50,200,50)
            surf = self.big_font.render(text, True, color)
            self.screen.blit(surf, (WIN_W//2-surf.get_width()//2, WIN_H//2-50))
            pygame.display.flip(); return

        for y in range(MAP_H):
            for x in range(MAP_W):
                sx = x*self.tile_size-self.camera_x; sy = y*self.tile_size-self.camera_y
                if -self.tile_size <= sx <= WIN_W+self.tile_size and -self.tile_size <= sy <= WIN_H+self.tile_size:
                    pygame.draw.rect(self.screen, COLORS.get(MAP[y][x],(0,0,0)), (sx,sy,self.tile_size,self.tile_size))
                    if MAP[y][x] == 8:
                        pygame.draw.circle(self.screen, (40,40,200), (sx+self.tile_size//2,sy+self.tile_size//2), 10)

        for e in self.enemies:
            sx = int(e[0]*self.tile_size-self.camera_x); sy = int(e[1]*self.tile_size-self.camera_y)
            pygame.draw.circle(self.screen, (200,30,30), (sx+self.tile_size//2,sy+self.tile_size//2), 12)
            hp_w = 20; hp_h = 3
            pygame.draw.rect(self.screen, (60,0,0), (sx+self.tile_size//2-hp_w//2,sy-5,hp_w,hp_h))
            pygame.draw.rect(self.screen, (0,200,0), (sx+self.tile_size//2-hp_w//2,sy-5,int(hp_w*e[2]/100),hp_h))

        px = int(self.px*self.tile_size-self.camera_x); py = int(self.py*self.tile_size-self.camera_y)
        pygame.draw.circle(self.screen, (0,200,0), (px+self.tile_size//2,py+self.tile_size//2), 14)
        pygame.draw.circle(self.screen, (100,255,100), (px+self.tile_size//2-3,py+self.tile_size//2-4), 4)

        texts = [f"HP: {{int(self.hp)}}/{{self.max_hp}}", f"LV: {{self.level}}",
                 f"GOLD: {{self.gold}}", f"ENEMIES: {{len(self.enemies)}}"]
        for i,t in enumerate(texts):
            self.screen.blit(self.font.render(t, True, (200,200,200)), (10,10+i*20))

        if self.dialog_active:
            pygame.draw.rect(self.screen, (0,0,0,180), (0,WIN_H-80,WIN_W,80))
            if self.dialog_index < len(self.dialog_lines):
                txt = self.dialog_lines[self.dialog_index]
                self.screen.blit(self.font.render(txt, True, (255,255,255)), (20,WIN_H-60))

        pygame.display.flip()

    def run(self):
        while self.running:
            dt = self.clock.tick(60)/1000.0
            self.handle_events()
            self.update(dt)
            self.render()
        pygame.quit()

if __name__ == "__main__":
    Game().run()
'''

    def _template_survival(self, **kw) -> str:
        return self._template_fps(**kw)

    def _template_roguelike(self, **kw) -> str:
        return self._template_rpg(**kw)

    def _get_renderer(self, config: GameConfig) -> str:
        if config.genre.value in ("fps", "shooter", "maze", "survival", "horror"):
            return "raycast_fps"
        return "topdown_2d"

    def _generate_systems(self, config: GameConfig) -> str:
        return ""

    def _generate_audio_code(self, audio_assets: dict | None) -> str:
        if not audio_assets:
            return ""
        parts = []
        for name, path in audio_assets.items():
            parts.append(f'        self.{name} = pygame.mixer.Sound(r"{path}")')
        return "\n".join(parts)

    def _map_to_str(self, tiles: list[list[int]]) -> str:
        return "[" + ",\n".join(
            "[" + ",".join(str(t) for t in row) + "]"
            for row in tiles
        ) + "]"

    @property
    def generated_count(self) -> int:
        return self._generated_count
