"""AI Code Engine — generates playable game source code with modular templates."""

from __future__ import annotations
from typing import Any, Optional
from pathlib import Path

from nicto_game.core.config import GameConfig, GameGenre, RenderMode
from nicto_game.core.types import GameMap, TileType


class CodeEngine:
    """Generates complete game source code from config and world data."""

    def __init__(self):
        self._generated_count = 0

    async def generate(self, config: GameConfig, game_map: GameMap,
                       characters: list | None = None,
                       quests: list | None = None,
                       audio_assets: dict | None = None) -> str:
        self._generated_count += 1
        renderer = self._get_renderer(config)
        systems = self._generate_systems(config)
        audio_code = self._generate_audio_code(audio_assets)

        w, h = game_map.width, game_map.height
        map_str = self._map_to_str(game_map.tiles)
        enemy_positions = []
        for k, v in game_map.spawn_points.items():
            if k.startswith("enemy_"):
                enemy_positions.append(v)

        player_start = game_map.spawn_points.get("player", (1, 1))
        items = []
        for k, v in game_map.spawn_points.items():
            if k.startswith("item_"):
                items.append(v)

        code = self._render_template(
            config=config,
            map_str=map_str,
            map_w=w, map_h=h,
            player_x=player_start[0], player_y=player_start[1],
            enemies=enemy_positions,
            items=items,
            renderer=renderer,
            systems=systems,
            audio_code=audio_code,
            has_characters=bool(characters),
            has_quests=bool(quests),
        )
        return code

    def _render_template(self, **kw) -> str:
        c = kw["config"]
        gm = kw["map_w"]
        h = kw["map_h"]

        return f'''"""
{c.name} — generated by NICTO Omega Game Engine
Genre: {c.genre.value} | Platform: {c.platform.value} | Render: {c.render_mode.value}
{c.description}
"""

import math, random, sys, pygame
from pygame.locals import *

# === CONFIG ===
WIN_W, WIN_H = {c.graphics.resolution_width}, {c.graphics.resolution_height}
FOV = {c.graphics.fov}
PLAYER_SPEED = {c.gameplay.speed}
PLAYER_HEALTH = {c.gameplay.health}
GRAVITY = {c.gameplay.gravity}
MAP_W, MAP_H = {gm}, {h}

# === MAP ===
MAP = {kw["map_str"]}

TILE_WALL, TILE_EMPTY, TILE_WATER, TILE_DOOR = 1, 0, 2, 4
TILE_ENEMY, TILE_ITEM, TILE_EXIT, TILE_NPC = 5, 6, 7, 8
WALKABLE = {{0, 4, 6, 7, 8}}

# === COLORS ===
COLORS = {{
    0: (40,40,40), 1: (100,100,100), 2: (20,60,120), 3: (20,80,30),
    4: (120,80,40), 5: (200,30,30), 6: (200,200,30), 7: (30,200,30),
    8: (30,30,200),
}}

# === GAME CLASS ===
class Game:
    def __init__(self):
        pygame.init()
        self.screen = pygame.display.set_mode((WIN_W, WIN_H))
        pygame.display.set_caption("{c.name}")
        self.clock = pygame.time.Clock()
        self.running = True
        self.px, self.py = {kw["player_x"]}.0, {kw["player_y"]}.0
        self.pa = 0.0
        self.hp = PLAYER_HEALTH
        self.max_hp = PLAYER_HEALTH
        self.score = 0
        self.keys = 0
        self.has_weapon = True
        self.game_over = False
        self.victory = False
        self.font = pygame.font.SysFont("Arial", 16)
        self.big_font = pygame.font.SysFont("Arial", 48)

        self.enemies = []
        for ex, ey in {kw["enemies"]}:
            self.enemies.append([ex + 0.5, ey + 0.5, 100.0, 0])

        self.items = []
        for ix, iy in {kw["items"]}:
            self.items.append([ix + 0.5, iy + 0.5, random.choice(["health", "key", "score", "weapon"])])

        self.ammo = 30
        self.last_shot = 0
        self.shoot_cooldown = 250

    def is_walkable(self, x, y):
        mx, my = int(x), int(y)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H:
            return MAP[my][mx] in WALKABLE
        return False

    def handle_events(self):
        for event in pygame.event.get():
            if event.type == QUIT:
                self.running = False
            if event.type == KEYDOWN:
                if event.key == K_ESCAPE:
                    self.running = False

    def update(self, dt):
        if self.game_over or self.victory:
            return

        keys = pygame.key.get_pressed()
        dx, dy = 0.0, 0.0
        if keys[K_w] or keys[K_UP]:
            dx += math.cos(self.pa) * PLAYER_SPEED * dt
            dy += math.sin(self.pa) * PLAYER_SPEED * dt
        if keys[K_s] or keys[K_DOWN]:
            dx -= math.cos(self.pa) * PLAYER_SPEED * dt
            dy -= math.sin(self.pa) * PLAYER_SPEED * dt
        if keys[K_a]:
            self.pa -= 2.5 * dt
        if keys[K_d]:
            self.pa += 2.5 * dt
        if keys[K_SPACE] or keys[K_LCTRL]:
            now = pygame.time.get_ticks()
            if now - self.last_shot > self.shoot_cooldown and self.ammo > 0:
                self.shoot()
                self.last_shot = now

        # Strafe
        if keys[K_q]:
            dx += math.cos(self.pa + math.pi / 2) * PLAYER_SPEED * 0.7 * dt
            dy += math.sin(self.pa + math.pi / 2) * PLAYER_SPEED * 0.7 * dt
        if keys[K_e]:
            dx += math.cos(self.pa - math.pi / 2) * PLAYER_SPEED * 0.7 * dt
            dy += math.sin(self.pa - math.pi / 2) * PLAYER_SPEED * 0.7 * dt

        if self.is_walkable(self.px + dx, self.py):
            self.px += dx
        if self.is_walkable(self.px, self.py + dy):
            self.py += dy

        # Mouse look
        mx, my = pygame.mouse.get_rel()
        self.pa += mx * 0.003

        self.check_items()
        self.update_enemies(dt)
        self.check_win()

    def shoot(self):
        self.ammo -= 1
        for e in self.enemies:
            dx = e[0] - self.px
            dy = e[1] - self.py
            dist = math.hypot(dx, dy)
            if dist < 8 and abs(math.atan2(dy, dx) - self.pa) % (math.pi * 2) < 0.3:
                e[2] -= 34.0

    def update_enemies(self, dt):
        for e in self.enemies[:]:
            if e[2] <= 0:
                self.enemies.remove(e)
                self.score += 100
                continue
            dx = self.px - e[0]
            dy = self.py - e[1]
            dist = math.hypot(dx, dy)
            if dist > 0 and dist < 12:
                speed = 1.5 * dt
                nx = e[0] + (dx / dist) * speed
                ny = e[1] + (dy / dist) * speed
                if self.is_walkable(nx, e[1]):
                    e[0] = nx
                if self.is_walkable(e[0], ny):
                    e[1] = ny
                if dist < 0.8:
                    self.hp -= 8 * dt
                    if self.hp <= 0:
                        self.hp = 0
                        self.game_over = True

    def check_items(self):
        for item in self.items[:]:
            dx = item[0] - self.px
            dy = item[1] - self.py
            if math.hypot(dx, dy) < 0.6:
                if item[2] == "health":
                    self.hp = min(self.max_hp, self.hp + 25)
                elif item[2] == "key":
                    self.keys += 1
                elif item[2] == "score":
                    self.score += 50
                elif item[2] == "weapon":
                    self.has_weapon = True
                self.items.remove(item)

    def check_win(self):
        mx, my = int(self.px), int(self.py)
        if 0 <= mx < MAP_W and 0 <= my < MAP_H and MAP[my][mx] == 7:
            self.victory = True

    def render(self):
        if self.game_over or self.victory:
            self.screen.fill((10, 10, 10))
            text = "GAME OVER" if self.game_over else "VICTORY!"
            color = (200, 50, 50) if self.game_over else (50, 200, 50)
            surf = self.big_font.render(text, True, color)
            self.screen.blit(surf, (WIN_W // 2 - surf.get_width() // 2, WIN_H // 2 - 50))
            surf2 = self.font.render("Press ESC to exit", True, (200, 200, 200))
            self.screen.blit(surf2, (WIN_W // 2 - surf2.get_width() // 2, WIN_H // 2 + 10))
            pygame.display.flip()
            return

        self.render_raycast()
        self.render_hud()
        self.render_minimap()
        pygame.display.flip()

    def render_raycast(self):
        for x in range(WIN_W):
            ray_angle = self.pa - FOV / 2 + (x / WIN_W) * FOV
            sin_a, cos_a = math.sin(ray_angle), math.cos(ray_angle)
            dist = 0.0
            hit = False
            while not hit and dist < 20:
                dist += 0.05
                tx = int(self.px + cos_a * dist)
                ty = int(self.py + sin_a * dist)
                if 0 <= tx < MAP_W and 0 <= ty < MAP_H:
                    if MAP[ty][tx] == TILE_WALL:
                        hit = True
                    elif MAP[ty][tx] == TILE_DOOR and dist > 0.5:
                        hit = True
                else:
                    hit = True
                    dist = 20

            # Fix fisheye
            dist *= math.cos(ray_angle - self.pa)
            wall_h = int(WIN_H / max(dist, 0.1))
            color_shade = max(30, min(255, 255 - dist * 12))
            wall_color = (color_shade, color_shade // 2, color_shade // 3)
            ceiling = (color_shade // 4, color_shade // 4, color_shade // 2)
            floor_c = (color_shade // 3, color_shade // 3, color_shade // 3)

            pygame.draw.line(self.screen, ceiling, (x, 0), (x, WIN_H // 2 - wall_h // 2))
            pygame.draw.line(self.screen, wall_color, (x, WIN_H // 2 - wall_h // 2),
                             (x, WIN_H // 2 + wall_h // 2))
            pygame.draw.line(self.screen, floor_c, (x, WIN_H // 2 + wall_h // 2),
                             (x, WIN_H))

        # Crosshair
        cx, cy = WIN_W // 2, WIN_H // 2
        pygame.draw.line(self.screen, (0, 255, 0), (cx - 8, cy), (cx + 8, cy), 2)
        pygame.draw.line(self.screen, (0, 255, 0), (cx, cy - 8), (cx, cy + 8), 2)

    def render_hud(self):
        hp_color = (0, 255, 0) if self.hp > 50 else (255, 255, 0) if self.hp > 25 else (255, 0, 0)
        texts = [
            f"HP: {{int(self.hp)}}", f"SCORE: {{self.score}}",
            f"ENEMIES: {{len(self.enemies)}}", f"AMMO: {{self.ammo}}",
        ]
        for i, t in enumerate(texts):
            surf = self.font.render(t, True, (200, 200, 200))
            self.screen.blit(surf, (10, 10 + i * 20))

        # Health bar
        bar_w, bar_h = 150, 12
        pygame.draw.rect(self.screen, (60, 60, 60), (10, 100, bar_w, bar_h))
        hp_w = int((self.hp / self.max_hp) * bar_w)
        pygame.draw.rect(self.screen, hp_color, (10, 100, hp_w, bar_h))

    def render_minimap(self):
        mm_size = 120
        mm_tile = max(1, mm_size // max(MAP_W, MAP_H))
        mm_x, mm_y = WIN_W - mm_size - 10, 10
        for my in range(MAP_H):
            for mx in range(MAP_W):
                c = COLORS.get(MAP[my][mx], (0, 0, 0))
                px = mm_x + mx * mm_tile
                py = mm_y + my * mm_tile
                pygame.draw.rect(self.screen, c, (px, py, mm_tile, mm_tile))

        # Player on minimap
        pmx = mm_x + int(self.px * mm_tile)
        pmy = mm_y + int(self.py * mm_tile)
        pygame.draw.circle(self.screen, (0, 255, 0), (pmx, pmy), 3)

    def run(self):
        while self.running:
            dt = self.clock.tick(60) / 1000.0
            self.handle_events()
            self.update(dt)
            self.render()
        pygame.quit()


if __name__ == "__main__":
    Game().run()
'''

    def _get_renderer(self, config: GameConfig) -> str:
        return "raycast_fps"

    def _generate_systems(self, config: GameConfig) -> str:
        return ""

    def _generate_audio_code(self, audio_assets: dict | None) -> str:
        if not audio_assets:
            return ""
        parts = []
        for name, path in audio_assets.items():
            parts.append(f'        self.{name} = pygame.mixer.Sound(r"{path}")')
        return "\n".join(parts)

    def _map_to_str(self, tiles: list[list[int]]) -> str:
        return "[" + ",\n".join(
            "[" + ",".join(str(t) for t in row) + "]"
            for row in tiles
        ) + "]"

    @property
    def generated_count(self) -> int:
        return self._generated_count
