#!/usr/bin/env python3
"""
NICTO Real AI — Fine-Tuning Pipeline
Trains a foundation model using Unsloth LoRA on NICTO ChatML training data.
Dual-mode: runs locally (CPU demo) or submits to cloud GPU.
"""
import json, os, sys, subprocess, platform
from pathlib import Path

HERE = Path(__file__).parent
CONFIG_PATH = HERE / "hardware_config.json"
DATA_PATH = HERE / "training_data" / "nicto_chatml.jsonl"
OUTPUT_DIR = HERE / "nicto_outputs" / "models"


def load_config():
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH) as f:
            return json.load(f)
    return {}


def check_gpu():
    try:
        import torch
        if torch.cuda.is_available():
            return True, torch.cuda.get_device_name(0)
        return False, None
    except ImportError:
        return False, None


def check_unsloth():
    try:
        import unsloth
        return True
    except ImportError:
        return False


def write_training_script(config: dict) -> str:
    """Generate the actual Unsloth training Python script."""
    model_name = config.get("base_model", "Qwen/Qwen2.5-1.5B-Instruct")
    output_path = str(OUTPUT_DIR / "nicto_lora")
    data_path = str(DATA_PATH)

    script = rf'''#!/usr/bin/env python3
"""NICTO Unsloth Fine-Tuning — Auto-generated by train_nicto.py"""
import os, sys, json, torch
sys.path.insert(0, r"{str(HERE)}")

os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"

# Load training data
data_path = r"{data_path}"
if not os.path.exists(data_path):
    # Generate it
    from build_training_data import main as build
    build()

with open(data_path, "r", encoding="utf-8") as f:
    raw_data = [json.loads(line) for line in f if line.strip()]

print(f"Loaded {{len(raw_data)}} training examples.")

# Unsloth imports
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template, train_on_responses_only
from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer
import torch

max_seq_length = 2048
dtype = torch.bfloat16 if is_bfloat16_supported() else torch.float16
load_in_4bit = True

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="{model_name}",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
)

tokenizer = get_chat_template(
    tokenizer,
    chat_template="chatml",
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
    use_rslora=True,
    loftq_config=None,
)

# Format dataset
def format_func(examples):
    texts = examples["text"]
    return {{"text": [t + tokenizer.eos_token if not t.endswith(tokenizer.eos_token) else t for t in texts]}}

dataset = Dataset.from_list(raw_data)
dataset = dataset.map(format_func, batched=True)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    dataset_num_proc=2,
    packing=False,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        num_train_epochs=3,
        learning_rate=2e-4,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        output_dir=r"{output_path}",
        report_to="none",
    ),
)

trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\\n",
    response_part="<|im_start|>assistant\\n",
)

print("Starting training...")
trainer_stats = trainer.train()
print(f"Training complete. Loss: {{trainer_stats.training_loss:.4f}}")

# Save LoRA adapters (small)
model.save_pretrained(r"{output_path}")
tokenizer.save_pretrained(r"{output_path}")
print(f"LoRA adapters saved to {{output_path}}")

# Save merged 16-bit (full)
merge_path = r"{output_path}" + "_merged"
model.save_pretrained_merged(merge_path, tokenizer)
print(f"Merged model saved to {{merge_path}}")

# Export GGUF
gguf_path = r"{output_path}" + "_gguf"
model.save_pretrained_gguf(gguf_path, tokenizer, quantization_method="q4_k_m")
print(f"GGUF model saved to {{gguf_path}}")

print("\\n=== Training Summary ===")
print(f"  Model: {model_name}")
print(f"  Examples: {{len(raw_data)}}")
print(f"  Epochs: 3")
print(f"  Loss: {{trainer_stats.training_loss:.4f}}")
'''
    return script


def run_cpu_demo():
    """Run a small CPU-compatible demo training."""
    print("=" * 60)
    print("NICTO TRAINING — CPU DEMO MODE")
    print("=" * 60)

    if not DATA_PATH.exists():
        print("Generating training data first...")
        from build_training_data import main as build
        build()

    data_path = str(DATA_PATH)
    with open(data_path, "r", encoding="utf-8") as f:
        data = [json.loads(line) for line in f if line.strip()]

    print(f"\nTraining data: {len(data)} examples loaded from {data_path}")
    print(f"\nCPU Demo Summary:")
    print(f"  To train on cloud GPU:")
    print(f"    1. Upload nicto_neural/ to cloud VM")
    print(f"    2. Run: python train_nicto.py --mode gpu")
    print(f"    3. Download LoRA adapters from nicto_outputs/models/")
    print(f"\n  Recommended cloud providers:")
    print(f"    - RunPod: $0.34/hr (RTX 4090, 24GB VRAM)")
    print(f"    - Lambda Labs: $0.29/hr (RTX 4090)")
    print(f"    - Colab: Free T4 (16GB VRAM)")
    print(f"    - Vast.ai: $0.15/hr (RTX 3090)")
    print()
    return {"status": "cpu_demo", "examples": len(data)}


def run_gpu_train():
    """Run actual Unsloth training."""
    if not check_unsloth():
        print("ERROR: Unsloth not installed. Run:")
        print("  pip install unsloth unsloth_zoo")
        sys.exit(1)

    config = load_config()
    if not config:
        print("No hardware_config.json found. Running setup...")
        subprocess.run([sys.executable, str(HERE / "setup_real_ai.py")])
        config = load_config()

    script = write_training_script(config)
    script_path = HERE / "_run_train.py"
    with open(script_path, "w") as f:
        f.write(script)

    print("Starting Unsloth training...")
    result = subprocess.run([sys.executable, str(script_path)])
    if result.returncode == 0:
        print("Training completed successfully!")
    else:
        print(f"Training failed with code {result.returncode}")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="NICTO Fine-Tuning Pipeline")
    parser.add_argument("--mode", choices=["cpu", "gpu", "script"], default="auto",
                        help="cpu: demo, gpu: real training, script: generate training script")
    args = parser.parse_args()

    has_gpu, gpu_name = check_gpu()
    mode = args.mode
    if mode == "auto":
        mode = "gpu" if has_gpu else "cpu"

    print(f"NICTO Training Pipeline — Mode: {mode}")
    if mode == "gpu" and has_gpu:
        print(f"  GPU detected: {gpu_name}")
    elif mode == "gpu" and not has_gpu:
        print("  ERROR: GPU mode requested but no GPU available.")
        print("  Run with --mode cpu for demo or deploy to cloud GPU.")
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if mode == "gpu":
        run_gpu_train()
    elif mode == "cpu":
        run_cpu_demo()
    elif mode == "script":
        config = load_config()
        script = write_training_script(config or {"base_model": "Qwen/Qwen2.5-1.5B-Instruct"})
        script_path = HERE / "run_on_cloud.py"
        with open(script_path, "w") as f:
            f.write(script)
        print(f"Training script written to {script_path}")
        print("Upload to cloud GPU and run: python run_on_cloud.py")


if __name__ == "__main__":
    main()
