"""Knowledge Loader — pre-built knowledge collections for NICTO's intelligence layer.

Provides 8 collections with 195+ entries covering programming languages,
framework patterns, app templates, database patterns, DevOps patterns,
UI patterns, testing patterns, and cloud patterns.
"""

import json
import os
from pathlib import Path
from typing import Optional

from nikto.knowledge.engine import KnowledgeEngine


# ═══════════════════════════════════════════════════
# COLLECTION 1 — PROGRAMMING LANGUAGES (50+ entries)
# ═══════════════════════════════════════════════════

PROGRAMMING_LANGUAGES = [
    # ── C ──
    {"topic": "c_memory", "fact": "C memory model: stack (automatic, LIFO, function-scoped) vs heap (manual, malloc/calloc/realloc/free). malloc returns void*, calloc zero-initializes, realloc resizes. Always check NULL return. Use valgrind --leak-check=full to detect leaks. Buffer overflows occur when writing past allocated bounds — use strncpy over strcpy, snprintf over sprintf.", "confidence": 0.95},
    {"topic": "c_pointers", "fact": "C pointers: pointer arithmetic adds sizeof(type) per increment. Double pointers (int **pp) for 2D arrays or modifying pointer args. Function pointers: int (*fp)(int,int) = &add; fp(1,2). void* is generic pointer requiring cast. const int *p (data const) vs int *const p (pointer const) vs const int *const p (both).", "confidence": 0.95},
    {"topic": "c_structs", "fact": "C structures: padding aligns members to natural boundaries (4-byte int at 4-byte offset). Use __attribute__((packed)) or #pragma pack to disable. Bitfields: struct { unsigned flag:1; unsigned value:7; }. Unions share memory — sizeof(union) = max member size. typedef struct Node { int data; struct Node *next; } Node; for self-referential types.", "confidence": 0.95},
    {"topic": "c_compilation", "fact": "C compilation flags: gcc -O2 (optimize), -Wall -Wextra -Wpedantic (warnings), -g (debug symbols), -fsanitize=address (ASAN for memory errors), -fsanitize=undefined (UBSAN). Makefile: CC=gcc; CFLAGS=-Wall -O2; %.o: %.c; $(CC) $(CFLAGS) -c $< -o $@. Static libs: ar rcs libfoo.a foo.o. Shared: gcc -shared -fPIC -o libfoo.so foo.c.", "confidence": 0.95},
    {"topic": "c_patterns", "fact": "C patterns: opaque pointers (forward-declare struct in header, define in .c for encapsulation). Error handling: return int error codes, set errno, perror() for messages. POSIX threads: pthread_create(&tid, NULL, func, arg); pthread_join(tid, NULL); pthread_mutex_lock/unlock for synchronization. Signal handling: signal(SIGINT, handler) or sigaction().", "confidence": 0.95},
    # ── C++ ──
    {"topic": "cpp_oop", "fact": "C++ OOP: virtual functions enable polymorphism via vtable (per-class pointer table). Pure virtual: virtual void f() = 0; makes class abstract. Multiple inheritance uses virtual base classes to solve diamond problem. Constructor init-list: Foo(int x) : member(x) {}. Rule of 5: destructor, copy ctor, copy assign, move ctor, move assign.", "confidence": 0.95},
    {"topic": "cpp_templates", "fact": "C++ templates: function template<typename T> T max(T a, T b); class template<typename K, typename V> class Map {}; template specialization for specific types. Variadic: template<typename... Args> void log(Args&&... args). SFINAE: std::enable_if_t<std::is_integral_v<T>, T> for conditional overloads. Concepts (C++20): template<std::integral T>.", "confidence": 0.95},
    {"topic": "cpp_stl", "fact": "C++ STL: vector (dynamic array, O(1) amortized push_back), map (red-black tree, O(log n)), unordered_map (hash table, O(1) average), set (unique sorted), deque (double-ended), list (doubly-linked). Algorithms: std::sort, std::find, std::transform, std::accumulate, std::remove_if + erase idiom. Iterators: begin/end, rbegin/rend.", "confidence": 0.95},
    {"topic": "cpp_modern", "fact": "C++ modern (11-20): auto type deduction, range-for (for(auto& x : vec)), lambda [capture](params){body}, unique_ptr (sole ownership, no copy), shared_ptr (ref-counted), weak_ptr (breaks cycles). Move semantics: std::move transfers ownership, rvalue refs T&&. std::optional<T>, std::variant<Types...>, std::filesystem::path. Structured bindings: auto [a,b] = pair.", "confidence": 0.95},
    {"topic": "cpp_build", "fact": "C++ build: CMake — cmake_minimum_required(VERSION 3.20); project(MyApp); add_executable(app main.cpp); target_link_libraries(app PRIVATE lib). Conan: conanfile.txt with [requires] and [generators]. RAII pattern: acquire in constructor, release in destructor — std::lock_guard, std::fstream, smart pointers all follow RAII.", "confidence": 0.95},
    # ── Rust ──
    {"topic": "rust_ownership", "fact": "Rust ownership: each value has exactly one owner. When owner goes out of scope, value is dropped. Assignment moves ownership (unless type implements Copy). Clone for explicit deep copy. References borrow without taking ownership: &T (immutable, multiple allowed) or &mut T (mutable, exclusive). Borrow checker enforces at compile time.", "confidence": 0.95},
    {"topic": "rust_enums", "fact": "Rust enums: enum Option<T> { Some(T), None }; enum Result<T,E> { Ok(T), Err(E) }. Pattern matching with match is exhaustive — must handle all variants. if let Some(val) = option { ... } for single-arm. while let for iterating. The ? operator propagates errors: let val = func()?; returns Err early if error.", "confidence": 0.95},
    {"topic": "rust_traits", "fact": "Rust traits: trait Display { fn fmt(&self, f: &mut Formatter) -> fmt::Result; }. impl Display for MyType { ... }. Trait objects: Box<dyn Trait> for dynamic dispatch. Bounds: fn process<T: Display + Clone>(item: T). where clauses for complex bounds. #[derive(Debug, Clone, Serialize, Deserialize)] for auto-implementation.", "confidence": 0.95},
    {"topic": "rust_cargo", "fact": "Rust Cargo: Cargo.toml [dependencies] section. cargo new/init, cargo build/run/test/bench. cargo clippy for lints, cargo fmt for formatting. Workspaces: [workspace] members = ['crate1', 'crate2']. Features: [features] default=['serde'] optional dependencies. cargo doc --open generates documentation.", "confidence": 0.95},
    {"topic": "rust_async", "fact": "Rust async: tokio runtime — #[tokio::main] async fn main(). async fn returns impl Future. .await to resolve futures. tokio::spawn for concurrent tasks. Channels: tokio::sync::mpsc, oneshot, broadcast. Pin<Box<dyn Future>> for trait objects. async-trait crate for async methods in traits. Error handling: anyhow for apps, thiserror for libs.", "confidence": 0.95},
    {"topic": "rust_crates", "fact": "Rust common crates: serde + serde_json (serialization), reqwest (HTTP client), sqlx (async DB with compile-time checked queries), axum (web framework with extractors and routing), clap (CLI with derive macros), tokio (async runtime), tracing (structured logging), tower (middleware). Unsafe: raw pointers *const/*mut T, FFI with extern 'C'.", "confidence": 0.95},
    # ── Assembly x86-64 ──
    {"topic": "asm_registers", "fact": "x86-64 registers: RAX/EAX/AX/AL (accumulator, return value), RBX (callee-saved), RCX (4th arg, counter), RDX (3rd arg), RSP (stack pointer), RBP (base pointer), RSI (2nd arg, source), RDI (1st arg, dest), R8-R9 (5th-6th args), R10-R15 (general). XMM0-15 for floating-point/SIMD.", "confidence": 0.9},
    {"topic": "asm_instructions", "fact": "x86-64 instructions: MOV dst,src; PUSH/POP (stack); ADD/SUB/IMUL/IDIV (arithmetic); CMP (compare, sets flags); JMP/JE/JNE/JG/JL/JGE/JLE (conditional jumps); CALL/RET (function call/return); LEA dst,[base+index*scale+disp] (address calc); XOR reg,reg (zero register); AND/OR/NOT/SHL/SHR (bitwise).", "confidence": 0.9},
    {"topic": "asm_calling", "fact": "System V AMD64 ABI (Linux): args in RDI, RSI, RDX, RCX, R8, R9 (integer/pointer). Floating-point in XMM0-7. Return in RAX (int) or XMM0 (float). Stack must be 16-byte aligned before CALL. Callee-saved: RBX, RBP, R12-R15. Prologue: push rbp; mov rbp,rsp; sub rsp,N. Epilogue: leave; ret.", "confidence": 0.9},
    {"topic": "asm_syscalls", "fact": "Linux x86-64 syscalls: RAX=syscall number, args in RDI/RSI/RDX/R10/R8/R9. Common: read=0, write=1, open=2, close=3, mmap=9, munmap=11, brk=12, execve=59, exit=60, socket=41, connect=42, accept=43. Invoke with 'syscall' instruction. Return in RAX (-errno on error).", "confidence": 0.9},
    # ── JavaScript ──
    {"topic": "js_core", "fact": "JavaScript core: var is function-scoped (hoisted), let/const are block-scoped (TDZ). Closures: inner function retains reference to outer scope. 'this' depends on call site — obj.fn() binds obj, standalone is undefined (strict) or window. Prototype chain: obj.__proto__ -> Constructor.prototype -> Object.prototype -> null. Event loop: call stack -> microtasks (Promise) -> macrotasks (setTimeout).", "confidence": 0.95},
    {"topic": "js_es6", "fact": "JavaScript ES6+: destructuring {a, b: renamed} = obj; [...rest] = arr. Spread: {...obj, key: val}. Optional chaining: obj?.prop?.method?.(). Nullish coalescing: val ?? default (only null/undefined). Array: map/filter/reduce/flatMap/find/some/every/includes. Object: Object.entries/keys/values/assign/fromEntries. Symbol for unique keys. Proxy/Reflect for metaprogramming.", "confidence": 0.95},
    {"topic": "js_async", "fact": "JavaScript async: Promises — new Promise((resolve, reject) => {}). then/catch/finally chaining. async/await — syntactic sugar over Promises. Promise.all (all settle), Promise.race (first settles), Promise.allSettled (all complete), Promise.any (first resolves). AbortController: const ac = new AbortController(); fetch(url, {signal: ac.signal}); ac.abort().", "confidence": 0.95},
    {"topic": "js_dom", "fact": "JavaScript DOM: document.querySelector/querySelectorAll (CSS selectors). addEventListener(event, handler, {capture, once, passive}). Event bubbling (target -> ancestors) vs capturing (ancestors -> target). Event delegation: listen on parent, check e.target. MutationObserver for DOM changes. IntersectionObserver for viewport visibility. requestAnimationFrame for smooth animations.", "confidence": 0.95},
    {"topic": "js_node", "fact": "Node.js: fs.readFile/writeFile/readdir (async), fs.createReadStream (streaming). path.join/resolve/basename/extname. http.createServer((req,res) => {}). events.EventEmitter for pub/sub. Streams: Readable/Writable/Transform/Duplex with pipe(). Buffer for binary data. child_process.exec/spawn. worker_threads for CPU-intensive tasks. cluster for multi-process.", "confidence": 0.95},
    {"topic": "js_modules", "fact": "JavaScript modules: ES modules — export default/named, import {x} from './mod.js', dynamic import('./mod.js'). CommonJS — module.exports = {}, const mod = require('./mod'). Package.json: 'type':'module' for ESM. Bundlers: webpack (config-heavy, mature), Vite (fast dev with ESBuild, Rollup prod), esbuild (ultra-fast), Rollup (tree-shaking).", "confidence": 0.95},
    # ── TypeScript ──
    {"topic": "ts_types", "fact": "TypeScript type system: primitives (string, number, boolean, null, undefined, symbol, bigint). Union: string | number. Intersection: A & B. Tuples: [string, number]. Enums: enum Dir { Up, Down }. Literal types: type Status = 'ok' | 'error'. Template literal: type Route = `/${string}`. Generics: function id<T>(arg: T): T { return arg; }.", "confidence": 0.95},
    {"topic": "ts_generics", "fact": "TypeScript generics: constraints with extends — <T extends HasId>. Conditional types: T extends string ? 'str' : 'other'. Mapped types: { [K in keyof T]: boolean }. infer keyword: type RetType<T> = T extends (...args: any[]) => infer R ? R : never. Utility: Partial<T>, Required<T>, Readonly<T>, Record<K,V>, Pick<T,K>, Omit<T,K>, Exclude, Extract, NonNullable, ReturnType<T>, Parameters<T>.", "confidence": 0.95},
    {"topic": "ts_advanced", "fact": "TypeScript advanced: discriminated unions — type Shape = {kind:'circle'; r:number} | {kind:'rect'; w:number; h:number}; switch(s.kind) for exhaustive checks. Branded types: type USD = number & {__brand:'USD'}. Builder pattern with generics for fluent APIs. Decorators (experimental): @Injectable, @Column. tsconfig strict mode enables all strict checks.", "confidence": 0.95},
    # ── React ──
    {"topic": "react_hooks", "fact": "React hooks: useState(initial) returns [state, setter]. useEffect(fn, deps) for side effects — [] runs once, [dep] on change, no array every render. useContext(Ctx) reads context. useReducer(reducer, init) for complex state. useRef(init) for mutable refs and DOM access. useMemo(fn, deps) caches computed values. useCallback(fn, deps) caches functions. Custom hooks extract reusable logic.", "confidence": 0.95},
    {"topic": "react_patterns", "fact": "React patterns: compound components (Parent provides context to Children). Render props: <DataFetcher render={data => <View data={data}/>}/>. HOC: const Enhanced = withAuth(Component). Controlled: value+onChange from parent. Uncontrolled: useRef for DOM values. Lifting state up: shared state in common ancestor. Composition over inheritance.", "confidence": 0.95},
    {"topic": "react_state", "fact": "React state management: Context API for simple global state (createContext + Provider + useContext). Redux Toolkit: createSlice({name,initialState,reducers}), configureStore, useSelector/useDispatch, createAsyncThunk for async, RTK Query for API caching. Zustand: create((set)=>({count:0, inc:()=>set(s=>({count:s.count+1}))})), simpler than Redux. Jotai: atom-based, bottom-up.", "confidence": 0.95},
    {"topic": "react_perf", "fact": "React performance: React.memo(Component) skips re-render if props unchanged. useMemo for expensive computations. useCallback for stable function refs. React.lazy(()=>import('./Heavy')) + Suspense for code splitting. react-window/react-virtuoso for list virtualization. Keys must be stable and unique. Avoid inline objects/arrays as props.", "confidence": 0.95},
    {"topic": "react_nextjs", "fact": "Next.js: App Router (app/ directory) — page.tsx, layout.tsx, loading.tsx, error.tsx. Server Components (default, no 'use client'): fetch data directly, zero client JS. Client Components ('use client'): interactivity, hooks, browser APIs. Route Handlers (route.ts): GET/POST/PUT/DELETE. SSG: generateStaticParams(). ISR: revalidate option. Middleware: middleware.ts for auth/redirects.", "confidence": 0.95},
    # ── Vue.js ──
    {"topic": "vue_composition", "fact": "Vue Composition API: setup() function or <script setup>. ref(val) for primitives (access .value), reactive(obj) for objects. computed(()=> derived). watch(source, (newVal, oldVal) => {}), watchEffect(()=> auto-tracks). provide('key', val) / inject('key') for dependency injection. Composables: export function useCounter() { const count = ref(0); return { count }; }.", "confidence": 0.95},
    {"topic": "vue_nuxt", "fact": "Nuxt.js: file-based routing (pages/ directory). Layouts (layouts/default.vue). Auto-imports for composables and components. useFetch(url) for SSR-safe data fetching. useAsyncData('key', ()=> $fetch(url)) with caching. Server routes (server/api/). Pinia: defineStore('id', { state:()=>({}), getters:{}, actions:{} }). Middleware: defineNuxtRouteMiddleware().", "confidence": 0.95},
    # ── Backend Frameworks ──
    {"topic": "express_node", "fact": "Express.js: const app = express(). Middleware: app.use(cors()), app.use(helmet()), app.use(express.json()). Routing: app.get('/api/users', handler), router.use('/api', apiRouter). Error handling: app.use((err,req,res,next)=> res.status(500).json({error:err.message})). body-parser for form data. multer for file uploads. passport.js for auth strategies (local, JWT, OAuth2).", "confidence": 0.95},
    {"topic": "django_python", "fact": "Django: models.py — class User(models.Model): name = models.CharField(max_length=100). views.py — def user_list(request): return JsonResponse(serializer.data). urls.py — path('api/users/', views.user_list). ORM: User.objects.filter(age__gte=18).order_by('-created'). Signals: post_save.connect(handler). REST Framework: ModelSerializer, ViewSet, Router. Channels for WebSocket.", "confidence": 0.95},
    {"topic": "flask_python", "fact": "Flask: app = Flask(__name__). @app.route('/api/users', methods=['GET']). Blueprints for modular apps. Application factory pattern: create_app(config). SQLAlchemy: db.Model, db.Column, db.relationship. Flask-Login for session auth. Flask-JWT-Extended for JWT. Celery for background tasks. Flask-Migrate for schema migrations.", "confidence": 0.95},
    {"topic": "spring_java", "fact": "Spring Boot: @SpringBootApplication main class. @RestController + @RequestMapping('/api'). @GetMapping/@PostMapping/@PutMapping/@DeleteMapping. @Autowired for DI. JPA: @Entity, @Repository extends JpaRepository<T,ID>. @Service for business logic. Spring Security: SecurityFilterChain bean, JWT filter. Maven: pom.xml with spring-boot-starter-web dependency.", "confidence": 0.95},
    {"topic": "laravel_php", "fact": "Laravel: php artisan make:model User -mcr (model+migration+controller+resource). Eloquent ORM: User::where('age','>',18)->orderBy('name')->get(). Blade templates: @extends('layout') @section('content'). Routes: Route::resource('users', UserController::class). Middleware: auth, throttle. Sanctum for SPA auth, Passport for OAuth. Queue: dispatch(new ProcessJob($data)).", "confidence": 0.95},
    {"topic": "rails_ruby", "fact": "Ruby on Rails: rails new app --api. rails generate scaffold User name:string email:string. ActiveRecord: User.where(active: true).order(created_at: :desc). Routes: resources :users. Controllers: render json: @users. RSpec: describe User do; it 'validates name' do; end; end. Devise for auth. Active Job for background. Action Cable for WebSocket.", "confidence": 0.95},
    {"topic": "go_web", "fact": "Go web (net/http + Gin): http.HandleFunc('/api', handler); http.ListenAndServe(':8080', nil). Gin: r := gin.Default(); r.GET('/users', getUsers); r.Run(':8080'). Middleware: r.Use(cors.Default()). JSON binding: c.ShouldBindJSON(&user). GORM: db.AutoMigrate(&User{}); db.Create(&user); db.Find(&users). goroutines: go processAsync(data).", "confidence": 0.95},
    {"topic": "dotnet_csharp", "fact": ".NET Core: [ApiController] [Route('api/[controller]')]. Action methods with [HttpGet], [HttpPost]. Entity Framework Core: DbContext, DbSet<T>, migrations (dotnet ef migrations add Init). LINQ: users.Where(u => u.Age > 18).OrderBy(u => u.Name). SignalR for real-time. Identity for auth. Dependency injection in Program.cs: builder.Services.AddScoped<IUserService, UserService>().", "confidence": 0.95},
    # ── Mobile ──
    {"topic": "react_native", "fact": "React Native: View, Text, TextInput, ScrollView, FlatList (virtualized), TouchableOpacity/Pressable. React Navigation: createStackNavigator, createBottomTabNavigator, createDrawerNavigator, deep linking. Native modules: Camera (react-native-camera), Location (expo-location), Notifications (expo-notifications), AsyncStorage, SecureStore. Expo vs bare workflow. EAS Build for CI/CD.", "confidence": 0.95},
    {"topic": "flutter_dart", "fact": "Flutter/Dart: StatelessWidget (immutable UI), StatefulWidget (mutable with setState). Widget tree composition. State management: Provider (ChangeNotifierProvider), Riverpod (ref.watch/read), BLoC (Cubit + BlocBuilder). Dart: null safety (?.), async/await, Streams, Isolates for parallelism, mixins. Navigation: GoRouter. Platform channels for native iOS/Android code. flutter build apk/ipa.", "confidence": 0.95},
    {"topic": "kotlin_android", "fact": "Kotlin Android: Jetpack Compose — @Composable fun Greeting(name: String) { Text('Hello $name') }. State: remember { mutableStateOf(0) }, by remember. LazyColumn for lists. Navigation: NavHost + composable routes. MVVM: ViewModel + StateFlow + collectAsState(). Hilt for DI: @HiltViewModel, @Inject. Room for DB. Retrofit for HTTP. Coil for images.", "confidence": 0.95},
    {"topic": "swift_ios", "fact": "Swift iOS: SwiftUI — struct ContentView: View { @State var count = 0; var body: some View { VStack { Text('\\(count)'); Button('Tap') { count += 1 } } } }. @Binding for child views. @ObservedObject/@StateObject for ObservableObject. @EnvironmentObject for global. NavigationStack + NavigationLink. List/Form. Core Data for persistence. URLSession + Codable for networking.", "confidence": 0.95},
    # ── Scripting ──
    {"topic": "powershell", "fact": "PowerShell: cmdlets — Get-Process, Set-Item, Invoke-WebRequest, Get-ADUser, Get-ADComputer. Pipeline: Get-Process | Where-Object {$_.CPU -gt 100} | Sort-Object CPU -Descending | Select-Object Name,CPU. Remoting: Invoke-Command -ComputerName srv1 -ScriptBlock { Get-Service }. Modules: Import-Module ActiveDirectory. Error: try/catch/finally. Profiles: $PROFILE for auto-load.", "confidence": 0.9},
    {"topic": "lua_scripting", "fact": "Lua: tables serve as arrays ({1,2,3}) and dicts ({key='val'}). Metatables: setmetatable(t, {__index=proto, __newindex=fn, __call=fn}). 1-based indexing. Coroutines: coroutine.create/resume/yield. Modules: local M = {}; function M.foo() end; return M. Love2D: love.load(), love.update(dt), love.draw(), love.keypressed(key). Lightweight embedding via C API: lua_pushstring, lua_pcall.", "confidence": 0.9},
    # ── SQL ──
    {"topic": "sql_advanced", "fact": "SQL advanced: CTEs — WITH cte AS (SELECT ...) SELECT * FROM cte. Window functions: ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salary DESC), RANK(), DENSE_RANK(), LAG(col, 1), LEAD(col, 1), SUM(col) OVER(ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW). CASE WHEN cond THEN val ELSE default END. COALESCE(a, b, c) for first non-null.", "confidence": 0.95},
    {"topic": "sql_postgres", "fact": "PostgreSQL: JSONB ops — col->>'key', col @> '{\"key\":\"val\"}', jsonb_array_elements(). Full-text: to_tsvector('english', text) @@ to_tsquery('search & terms'). LATERAL joins for correlated subqueries. Array: ARRAY[1,2,3], unnest(), array_agg(). Row-level security: ALTER TABLE t ENABLE ROW LEVEL SECURITY; CREATE POLICY. EXPLAIN ANALYZE for query planning.", "confidence": 0.95},
    # ── GraphQL ──
    {"topic": "graphql", "fact": "GraphQL: type Query { user(id: ID!): User }; type User { id: ID!; name: String!; posts: [Post!]! }. Resolvers: Query: { user: (_, {id}) => db.findUser(id) }. Mutations for writes. Subscriptions for real-time (WebSocket). DataLoader batches N+1 queries. Apollo Server (Node), Strawberry (Python), Hasura (auto-generate from Postgres).", "confidence": 0.95},
    # ── Solidity ──
    {"topic": "solidity", "fact": "Solidity: pragma solidity ^0.8.0; contract Token is ERC20 { constructor() ERC20('Name','SYM') { _mint(msg.sender, 1000000 * 10**decimals()); } }. Storage vs memory vs calldata. Modifiers: modifier onlyOwner { require(msg.sender == owner); _; }. Events: event Transfer(address indexed from, address indexed to, uint256 value); emit Transfer(). Security: reentrancy guard, checks-effects-interactions pattern. Hardhat/Foundry for testing.", "confidence": 0.9},
    # ── Functional ──
    {"topic": "haskell", "fact": "Haskell: algebraic data types — data Maybe a = Nothing | Just a. Type classes: class Eq a where (==) :: a -> a -> Bool. Pattern matching in function definitions. Guards: | x > 0 = 'positive'. List comprehensions: [x*2 | x <- [1..10], even x]. Lazy evaluation by default. Monads: IO, Maybe, Either, State, Reader. do-notation for monadic sequencing. Point-free: sum = foldl (+) 0.", "confidence": 0.9},
    {"topic": "elixir_otp", "fact": "Elixir/OTP: processes — spawn(fn -> ... end). GenServer: use GenServer; def handle_call(:get, _from, state), do: {:reply, state, state}. Supervisor trees for fault tolerance: children = [{MyWorker, []}]; Supervisor.start_link(children, strategy: :one_for_one). Phoenix: controllers, LiveView (real-time UI without JS), channels, Ecto schemas + changesets + Repo.", "confidence": 0.9},
    {"topic": "go_concurrency", "fact": "Go concurrency: go func() { ... }() launches goroutine. Channels: ch := make(chan int); ch <- 42; val := <-ch. Buffered: make(chan int, 10). Select: select { case v := <-ch1: ...; case ch2 <- val: ...; default: ... }. sync.WaitGroup: wg.Add(1); go func() { defer wg.Done(); ... }(); wg.Wait(). sync.Mutex for shared state. context.WithCancel/WithTimeout for cancellation.", "confidence": 0.95},
    {"topic": "go_patterns", "fact": "Go patterns: error handling — if err != nil { return fmt.Errorf('doing x: %w', err) }. errors.Is/As for unwrapping. Interfaces: type Reader interface { Read(p []byte) (n int, err error) }. Empty interface any (= interface{}). Type assertion: val, ok := i.(string). Standard lib: net/http, encoding/json, os, context, testing. Popular: gin, gorm, cobra, viper, zap.", "confidence": 0.95},
]

# ═══════════════════════════════════════════════════
# COLLECTION 2 — FRAMEWORK PATTERNS (30+ entries)
# ═══════════════════════════════════════════════════

FRAMEWORK_PATTERNS = [
    {"topic": "nextjs_app_router", "fact": "Next.js App Router pattern: app/layout.tsx (root layout with html/body), app/page.tsx (home), app/dashboard/page.tsx (nested route). Server Components fetch data: async function Page() { const data = await fetch(url); return <div>{data.title}</div>; }. Client Components for interactivity: 'use client'; export default function Counter() { const [c, setC] = useState(0); ... }.", "confidence": 0.95},
    {"topic": "express_middleware", "fact": "Express middleware chain: app.use(cors({origin: 'http://localhost:3000', credentials: true})); app.use(helmet()); app.use(express.json({limit: '10mb'})); app.use(rateLimit({windowMs: 15*60*1000, max: 100})); const auth = (req,res,next) => { const token = req.headers.authorization?.split(' ')[1]; if(!token) return res.status(401).json({error:'No token'}); jwt.verify(token, SECRET, (err,user) => { req.user = user; next(); }); };", "confidence": 0.95},
    {"topic": "fastapi_pattern", "fact": "FastAPI pattern: from fastapi import FastAPI, Depends, HTTPException; app = FastAPI(); class UserCreate(BaseModel): name: str; email: EmailStr; @app.post('/users', response_model=UserResponse, status_code=201); async def create_user(user: UserCreate, db: Session = Depends(get_db)): db_user = User(**user.dict()); db.add(db_user); db.commit(); return db_user. Background tasks: background_tasks.add_task(send_email, email).", "confidence": 0.95},
    {"topic": "django_rest", "fact": "Django REST Framework: class UserSerializer(serializers.ModelSerializer): class Meta: model = User; fields = '__all__'. class UserViewSet(viewsets.ModelViewSet): queryset = User.objects.all(); serializer_class = UserSerializer; permission_classes = [IsAuthenticated]. router = DefaultRouter(); router.register('users', UserViewSet); urlpatterns = [path('api/', include(router.urls))].", "confidence": 0.95},
    {"topic": "redux_toolkit", "fact": "Redux Toolkit: const userSlice = createSlice({ name: 'users', initialState: { list: [], loading: false }, reducers: { addUser: (state, action) => { state.list.push(action.payload); } }, extraReducers: (builder) => { builder.addCase(fetchUsers.pending, (state) => { state.loading = true; }); } }); const fetchUsers = createAsyncThunk('users/fetch', async () => (await fetch('/api/users')).json());", "confidence": 0.95},
    {"topic": "gin_go_pattern", "fact": "Gin Go pattern: r := gin.Default(); r.Use(corsMiddleware()); api := r.Group('/api'); api.Use(authMiddleware()); api.GET('/users', getUsers); api.POST('/users', createUser); func getUsers(c *gin.Context) { var users []User; db.Find(&users); c.JSON(200, users) }. Binding: var input CreateUserInput; if err := c.ShouldBindJSON(&input); err != nil { c.JSON(400, gin.H{'error': err.Error()}); return }.", "confidence": 0.95},
    {"topic": "spring_rest", "fact": "Spring Boot REST: @RestController @RequestMapping('/api/users') public class UserController { @Autowired private UserService service; @GetMapping public List<User> getAll() { return service.findAll(); } @PostMapping public ResponseEntity<User> create(@Valid @RequestBody UserDTO dto) { return ResponseEntity.status(201).body(service.create(dto)); } @DeleteMapping('/{id}') public void delete(@PathVariable Long id) { service.delete(id); } }", "confidence": 0.95},
    {"topic": "nestjs_pattern", "fact": "NestJS pattern: @Module({ imports: [TypeOrmModule.forFeature([User])], controllers: [UserController], providers: [UserService] }). @Controller('users') with @Get(), @Post(), @Body(), @Param(). @Injectable() class UserService { constructor(@InjectRepository(User) private repo: Repository<User>) {} async findAll(): Promise<User[]> { return this.repo.find(); } }. Guards: @UseGuards(JwtAuthGuard). Swagger: @ApiTags('users').", "confidence": 0.95},
    {"topic": "axum_rust_pattern", "fact": "Axum Rust: let app = Router::new().route('/users', get(list_users).post(create_user)).layer(CorsLayer::permissive()).with_state(pool); async fn list_users(State(pool): State<PgPool>) -> Json<Vec<User>> { let users = sqlx::query_as!(User, 'SELECT * FROM users').fetch_all(&pool).await.unwrap(); Json(users) }. Extractors: Path(id), Query(params), Json(body).", "confidence": 0.95},
    {"topic": "svelte_pattern", "fact": "Svelte pattern: <script> let count = 0; $: doubled = count * 2; function increment() { count += 1; } </script> <button on:click={increment}>{count} (doubled: {doubled})</button>. SvelteKit: +page.svelte, +page.server.ts (load function), +layout.svelte. Stores: writable(0), derived, readable. Transitions: <div transition:fade>.", "confidence": 0.9},
    {"topic": "tailwind_css", "fact": "Tailwind CSS patterns: responsive — sm:text-lg md:text-xl lg:text-2xl. Flexbox: flex items-center justify-between gap-4. Grid: grid grid-cols-3 gap-6. Hover/focus: hover:bg-blue-600 focus:ring-2. Dark mode: dark:bg-gray-900 dark:text-white. Custom: @apply in CSS or extend theme in tailwind.config.js. JIT mode for arbitrary values: w-[calc(100%-2rem)].", "confidence": 0.95},
    {"topic": "prisma_pattern", "fact": "Prisma ORM: schema.prisma — model User { id Int @id @default(autoincrement()); email String @unique; posts Post[] }. Client: const user = await prisma.user.create({ data: { email } }); const users = await prisma.user.findMany({ where: { active: true }, include: { posts: true }, orderBy: { createdAt: 'desc' } }). Migrations: npx prisma migrate dev.", "confidence": 0.95},
    {"topic": "sqlalchemy_pattern", "fact": "SQLAlchemy pattern: class User(Base): __tablename__ = 'users'; id = Column(Integer, primary_key=True); name = Column(String(100)). Session: with Session(engine) as session: user = session.query(User).filter(User.name == 'Alice').first(); session.add(User(name='Bob')); session.commit(). Async: from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine.", "confidence": 0.95},
    {"topic": "flutter_riverpod", "fact": "Flutter Riverpod: final counterProvider = StateNotifierProvider<CounterNotifier, int>((ref) => CounterNotifier()); class CounterNotifier extends StateNotifier<int> { CounterNotifier() : super(0); void increment() => state++; }. Consumer widget: ref.watch(counterProvider) to read, ref.read(counterProvider.notifier).increment() to modify. FutureProvider/StreamProvider for async.", "confidence": 0.9},
    {"topic": "compose_android", "fact": "Jetpack Compose: @Composable fun UserList(viewModel: UserVM = hiltViewModel()) { val users by viewModel.users.collectAsStateWithLifecycle(); LazyColumn { items(users) { user -> UserCard(user) } } }. Navigation: NavHost(navController, startDestination='home') { composable('home') { HomeScreen() }; composable('detail/{id}') { DetailScreen(it.arguments?.getString('id')) } }.", "confidence": 0.9},
    {"topic": "swiftui_pattern", "fact": "SwiftUI: struct UserListView: View { @StateObject var viewModel = UserViewModel(); var body: some View { NavigationStack { List(viewModel.users) { user in NavigationLink(user.name, value: user) }.navigationDestination(for: User.self) { user in UserDetailView(user: user) }.task { await viewModel.load() } } } }. @Published in ObservableObject, @Environment for app-wide state.", "confidence": 0.9},
    # Architecture patterns
    {"topic": "clean_architecture", "fact": "Clean Architecture: layers from inside out — Entities (business rules), Use Cases (application logic), Interface Adapters (controllers, gateways), Frameworks (DB, web, UI). Dependency rule: inner layers never know about outer layers. Ports and Adapters (Hexagonal): domain defines ports (interfaces), adapters implement them. This makes the core testable without infrastructure.", "confidence": 0.95},
    {"topic": "microservice_patterns", "fact": "Microservice patterns: API Gateway (single entry point, routing, auth). Service Discovery (Consul, etcd). Circuit Breaker (fail-fast, fallback). Saga pattern (distributed transactions via choreography or orchestration). Event Sourcing (store events, derive state). CQRS (separate read/write models). Sidecar (service mesh with Istio/Linkerd). Outbox pattern for reliable event publishing.", "confidence": 0.95},
    {"topic": "event_driven", "fact": "Event-driven architecture: Kafka — topics, partitions, consumer groups, exactly-once semantics. RabbitMQ — exchanges (direct, topic, fanout), queues, acknowledgments. NATS — pub/sub, request/reply, JetStream for persistence. Event schema: { type: 'OrderCreated', data: {...}, metadata: { timestamp, correlationId } }. Dead letter queue for failed processing.", "confidence": 0.95},
    {"topic": "cqrs_pattern", "fact": "CQRS (Command Query Responsibility Segregation): separate write model (normalized, consistent) from read model (denormalized, fast). Commands: CreateOrder, UpdateUser — go through command handler, validate, persist, emit events. Queries: GetOrderById, ListUsers — read from optimized projections (materialized views, Elasticsearch). Eventually consistent between write and read sides.", "confidence": 0.95},
    {"topic": "ddd_patterns", "fact": "Domain-Driven Design: Aggregate (cluster of entities with root), Value Object (immutable, equality by value), Entity (identity matters), Repository (collection-like interface for aggregates), Domain Service (stateless operations spanning aggregates), Domain Event (something that happened), Bounded Context (explicit boundary for a model), Ubiquitous Language (shared team vocabulary).", "confidence": 0.95},
    {"topic": "laravel_pattern", "fact": "Laravel pattern: php artisan make:model User -mcr (model, migration, controller, resource). Eloquent: User::where('active', true)->orderBy('name')->paginate(15). Routes: Route::apiResource('users', UserController::class). Middleware: Route::middleware(['auth:sanctum'])->group(...). Blade: @extends('layouts.app') @section('content') @foreach($users as $user) {{ $user->name }} @endforeach.", "confidence": 0.9},
    {"topic": "rails_pattern", "fact": "Ruby on Rails: rails generate scaffold User name:string email:string. RESTful routes: resources :users. Controller: class UsersController < ApplicationController; def index; @users = User.all; end. ActiveRecord: User.where(active: true).order(:name).limit(10). RSpec: describe User do; it { should validate_presence_of(:name) }; end. Devise for auth.", "confidence": 0.9},
    {"topic": "phoenix_elixir", "fact": "Phoenix LiveView: def render(assigns) do ~H\"<button phx-click='increment'><%= @count %></button>\". def handle_event('increment', _, socket) do {:noreply, update(socket, :count, &(&1 + 1))} end. Ecto: schema 'users' do field :name, :string; timestamps() end. Changesets for validation: cast(params, [:name]) |> validate_required([:name]).", "confidence": 0.9},
    {"topic": "htmx_pattern", "fact": "HTMX pattern: <button hx-post='/api/items' hx-target='#list' hx-swap='beforeend'>Add</button>. Server returns HTML fragments, not JSON. Attributes: hx-get, hx-post, hx-trigger, hx-target, hx-swap (innerHTML, outerHTML, beforeend, afterbegin), hx-confirm, hx-indicator. Combines with any server framework (Go, Python, Ruby). Minimal JavaScript approach.", "confidence": 0.9},
    {"topic": "graphql_apollo", "fact": "Apollo GraphQL: const typeDefs = gql`type Query { users: [User!]! } type User { id: ID!; name: String! }`; const resolvers = { Query: { users: () => db.users.findAll() } }; const server = new ApolloServer({ typeDefs, resolvers }). Client: const { data } = useQuery(GET_USERS); useMutation for writes. DataLoader for batching N+1 queries.", "confidence": 0.95},
    {"topic": "trpc_pattern", "fact": "tRPC: end-to-end typesafe APIs for TypeScript. Server: const appRouter = router({ user: { getAll: publicProcedure.query(() => db.user.findMany()), create: publicProcedure.input(z.object({ name: z.string() })).mutation(({ input }) => db.user.create({ data: input })) } }). Client: const { data } = trpc.user.getAll.useQuery(). No schema generation needed — types flow from server to client.", "confidence": 0.9},
    {"topic": "zustand_state", "fact": "Zustand state management: const useStore = create((set) => ({ count: 0, increment: () => set((s) => ({ count: s.count + 1 })), reset: () => set({ count: 0 }) })); In component: const count = useStore((s) => s.count); const increment = useStore((s) => s.increment). Persist middleware: create(persist((...) => ({}), { name: 'store' })). Simpler than Redux, no boilerplate.", "confidence": 0.9},
    {"topic": "tanstack_query", "fact": "TanStack Query (React Query): const { data, isLoading, error } = useQuery({ queryKey: ['users'], queryFn: () => fetch('/api/users').then(r => r.json()) }); useMutation for writes with onSuccess invalidation: const mutation = useMutation({ mutationFn: createUser, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['users'] }) }). Automatic caching, background refetch, pagination.", "confidence": 0.9},
    {"topic": "fiber_go_pattern", "fact": "Go Fiber: app := fiber.New(fiber.Config{Prefork: true}); app.Use(cors.New()); app.Get('/api/users', func(c *fiber.Ctx) error { return c.JSON(users) }); app.Post('/api/users', func(c *fiber.Ctx) error { var u User; if err := c.BodyParser(&u); err != nil { return c.Status(400).JSON(fiber.Map{'error': err.Error()}) }; return c.Status(201).JSON(u) }). Express-inspired API for Go.", "confidence": 0.9},
    {"topic": "hono_pattern", "fact": "Hono: lightweight, ultra-fast web framework for edge runtimes (Cloudflare Workers, Deno, Bun). const app = new Hono(); app.get('/api/users', (c) => c.json(users)); app.post('/api/users', async (c) => { const body = await c.req.json(); return c.json(body, 201); }). Built-in middleware: cors(), logger(), basicAuth(). Works on any JS runtime. ~14KB bundle.", "confidence": 0.9},
]

# ═══════════════════════════════════════════════════
# COLLECTION 3 — APP TEMPLATES (25 entries)
# ═══════════════════════════════════════════════════

APP_TEMPLATES = [
    {"topic": "rest_api_python", "fact": "FastAPI REST template: main.py — from fastapi import FastAPI, HTTPException; from pydantic import BaseModel; app = FastAPI(); class Item(BaseModel): name: str; price: float; items = {}; @app.post('/items/{id}'); def create(id: int, item: Item): items[id] = item; return item; @app.get('/items/{id}'); def read(id: int): if id not in items: raise HTTPException(404); return items[id]. Run: uvicorn main:app --reload.", "confidence": 0.95},
    {"topic": "rest_api_go", "fact": "Go Gin REST template: main.go — func main() { r := gin.Default(); r.GET('/api/items', getItems); r.POST('/api/items', createItem); r.Run(':8080') }; func getItems(c *gin.Context) { c.JSON(200, items) }; func createItem(c *gin.Context) { var item Item; if err := c.ShouldBindJSON(&item); err != nil { c.JSON(400, gin.H{'error': err.Error()}); return }; items = append(items, item); c.JSON(201, item) }. go.mod: module app; require github.com/gin-gonic/gin.", "confidence": 0.95},
    {"topic": "rest_api_node", "fact": "Express REST template: const express = require('express'); const app = express(); app.use(express.json()); let items = []; app.get('/api/items', (req,res) => res.json(items)); app.post('/api/items', (req,res) => { const item = {id: Date.now(), ...req.body}; items.push(item); res.status(201).json(item); }); app.listen(3000). package.json: {'scripts':{'start':'node index.js','dev':'nodemon index.js'}}.", "confidence": 0.95},
    {"topic": "rest_api_rust", "fact": "Axum REST template: #[tokio::main] async fn main() { let app = Router::new().route('/items', get(list).post(create)).with_state(Arc::new(Mutex::new(Vec::new()))); axum::Server::bind(&'0.0.0.0:3000'.parse().unwrap()).serve(app.into_make_service()).await.unwrap(); }. Cargo.toml: [dependencies] axum='0.7'; tokio={version='1',features=['full']}; serde={version='1',features=['derive']}; serde_json='1'.", "confidence": 0.95},
    {"topic": "graphql_node", "fact": "Apollo GraphQL template: const { ApolloServer } = require('@apollo/server'); const typeDefs = `type Query { users: [User] } type User { id: ID! name: String! }`; const resolvers = { Query: { users: () => db.getUsers() } }; const server = new ApolloServer({ typeDefs, resolvers }); server.listen(4000). DataLoader for N+1: new DataLoader(ids => db.getUsersByIds(ids)).", "confidence": 0.95},
    {"topic": "react_spa", "fact": "React SPA template (Vite): npm create vite@latest app -- --template react-ts. App.tsx: function App() { return <BrowserRouter><Routes><Route path='/' element={<Layout/>}><Route index element={<Home/>}/><Route path='dashboard' element={<Dashboard/>}/></Route></Routes></BrowserRouter> }. Auth context: createContext, useAuth hook, ProtectedRoute wrapper. TanStack Query for API calls.", "confidence": 0.95},
    {"topic": "flutter_app", "fact": "Flutter app template: main.dart — void main() => runApp(ProviderScope(child: MyApp())); class MyApp extends ConsumerWidget { Widget build(context, ref) { return MaterialApp.router(routerConfig: ref.watch(routerProvider), theme: ThemeData.light(useMaterial3: true)); } }. pubspec.yaml: dependencies: flutter_riverpod, go_router, dio, freezed_annotation. Dev: build_runner, freezed.", "confidence": 0.9},
    {"topic": "cli_python", "fact": "Python CLI template (Click): import click; @click.group() def cli(): pass; @cli.command() @click.argument('name') @click.option('--count', '-c', default=1, help='Repeat count') def greet(name, count): for _ in range(count): click.echo(f'Hello {name}!'). setup.py entry_points: {'console_scripts': ['mycli=mypackage.cli:cli']}. Rich for formatted output, tqdm for progress bars.", "confidence": 0.95},
    {"topic": "cli_go", "fact": "Go CLI template (Cobra): var rootCmd = &cobra.Command{Use: 'myapp', Short: 'My CLI app'}; var serveCmd = &cobra.Command{Use: 'serve', RunE: func(cmd *cobra.Command, args []string) error { port, _ := cmd.Flags().GetInt('port'); return startServer(port) }}; func init() { serveCmd.Flags().IntP('port', 'p', 8080, 'Port'); rootCmd.AddCommand(serveCmd) }. Viper for config: viper.ReadInConfig().", "confidence": 0.95},
    {"topic": "cli_rust", "fact": "Rust CLI template (Clap): use clap::Parser; #[derive(Parser)] #[command(name='myapp', about='My CLI')] struct Args { #[arg(short, long)] name: String, #[arg(short, long, default_value_t=1)] count: u8, }; fn main() { let args = Args::parse(); for _ in 0..args.count { println!('Hello {}!', args.name); } }. Cargo.toml: clap = { version = '4', features = ['derive'] }.", "confidence": 0.95},
    {"topic": "discord_bot", "fact": "Discord bot template (discord.py): import discord; from discord.ext import commands; bot = commands.Bot(command_prefix='!', intents=discord.Intents.all()); @bot.event; async def on_ready(): print(f'{bot.user} connected'); @bot.command(); async def ping(ctx): await ctx.send(f'Pong! {round(bot.latency*1000)}ms'); bot.run(os.getenv('DISCORD_TOKEN')). Slash commands: @bot.tree.command(); async def hello(interaction).", "confidence": 0.95},
    {"topic": "telegram_bot", "fact": "Telegram bot (python-telegram-bot): from telegram.ext import Application, CommandHandler, MessageHandler, filters; async def start(update, context): await update.message.reply_text('Hello!'); async def echo(update, context): await update.message.reply_text(update.message.text); app = Application.builder().token(TOKEN).build(); app.add_handler(CommandHandler('start', start)); app.add_handler(MessageHandler(filters.TEXT, echo)); app.run_polling().", "confidence": 0.95},
    {"topic": "smart_contract", "fact": "Solidity ERC-20 template: pragma solidity ^0.8.20; import '@openzeppelin/contracts/token/ERC20/ERC20.sol'; contract MyToken is ERC20 { constructor(uint256 initialSupply) ERC20('MyToken', 'MTK') { _mint(msg.sender, initialSupply * 10 ** decimals()); } }. Hardhat: npx hardhat init; npx hardhat test; npx hardhat run scripts/deploy.js --network sepolia. Foundry: forge test.", "confidence": 0.9},
    {"topic": "chrome_extension", "fact": "Chrome Extension (Manifest V3): manifest.json: {'manifest_version':3, 'name':'MyExt', 'version':'1.0', 'permissions':['activeTab','storage'], 'action':{'default_popup':'popup.html'}, 'background':{'service_worker':'background.js'}, 'content_scripts':[{'matches':['<all_urls>'],'js':['content.js']}]}. chrome.tabs.query, chrome.storage.local, chrome.runtime.sendMessage.", "confidence": 0.9},
    {"topic": "electron_app", "fact": "Electron template: main.js — const { app, BrowserWindow } = require('electron'); function createWindow() { const win = new BrowserWindow({ width: 800, height: 600, webPreferences: { preload: path.join(__dirname, 'preload.js'), nodeIntegration: false, contextIsolation: true } }); win.loadFile('index.html'); }; app.whenReady().then(createWindow). IPC: ipcMain.handle('read-file', async (e, path) => fs.readFileSync(path, 'utf-8')).", "confidence": 0.9},
    {"topic": "tauri_app", "fact": "Tauri template: cargo tauri init. src-tauri/src/main.rs: #[tauri::command] fn greet(name: &str) -> String { format!('Hello {}!', name) }; fn main() { tauri::Builder::default().invoke_handler(tauri::generate_handler![greet]).run(tauri::generate_context!()).unwrap(); }. Frontend (React): invoke('greet', { name: 'World' }).then(setMessage). Much smaller than Electron (~600KB vs ~100MB).", "confidence": 0.9},
    {"topic": "docker_microservice", "fact": "Docker microservice template: Dockerfile — FROM python:3.12-slim; WORKDIR /app; COPY requirements.txt .; RUN pip install --no-cache-dir -r requirements.txt; COPY . .; EXPOSE 8000; CMD ['uvicorn', 'main:app', '--host', '0.0.0.0']. docker-compose.yml: services: api: build: .; ports: ['8000:8000']; depends_on: [db]; db: image: postgres:16; environment: POSTGRES_PASSWORD: secret; volumes: [pgdata:/var/lib/postgresql/data].", "confidence": 0.95},
    {"topic": "k8s_deployment", "fact": "Kubernetes deployment: apiVersion: apps/v1; kind: Deployment; metadata: name: api; spec: replicas: 3; selector: matchLabels: app: api; template: spec: containers: - name: api; image: myapp:latest; ports: - containerPort: 8000; resources: limits: memory: 512Mi; cpu: 500m; env: - name: DB_URL; valueFrom: secretKeyRef: name: db-secret; key: url. Service: type: ClusterIP, port: 80, targetPort: 8000.", "confidence": 0.95},
    {"topic": "serverless_lambda", "fact": "AWS Lambda template: def handler(event, context): body = json.loads(event.get('body', '{}')); result = process(body); return {'statusCode': 200, 'headers': {'Content-Type': 'application/json'}, 'body': json.dumps(result)}. SAM template.yaml: Resources: MyFunction: Type: AWS::Serverless::Function; Properties: Handler: app.handler; Runtime: python3.12; Events: Api: Type: Api; Properties: Path: /process; Method: post.", "confidence": 0.9},
    {"topic": "websocket_server", "fact": "WebSocket server (Node): const WebSocket = require('ws'); const wss = new WebSocket.Server({ port: 8080 }); wss.on('connection', (ws) => { ws.on('message', (msg) => { const data = JSON.parse(msg); wss.clients.forEach(client => { if (client.readyState === WebSocket.OPEN) client.send(JSON.stringify({user: data.user, text: data.text})); }); }); }). Python: websockets.serve(handler, 'localhost', 8080).", "confidence": 0.95},
    {"topic": "grpc_service", "fact": "gRPC service: user.proto — syntax='proto3'; service UserService { rpc GetUser(GetUserRequest) returns (User); rpc ListUsers(ListUsersRequest) returns (stream User); }; message User { int32 id = 1; string name = 2; }. Go server: type server struct { pb.UnimplementedUserServiceServer }; func (s *server) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.User, error) { ... }. Python: grpcio + grpcio-tools.", "confidence": 0.9},
    {"topic": "unity_game", "fact": "Unity C# template: public class PlayerController : MonoBehaviour { [SerializeField] float speed = 5f; Rigidbody rb; void Start() { rb = GetComponent<Rigidbody>(); } void Update() { float h = Input.GetAxis('Horizontal'); float v = Input.GetAxis('Vertical'); rb.velocity = new Vector3(h, rb.velocity.y, v) * speed; } }. MonoBehaviour lifecycle: Awake -> Start -> Update -> FixedUpdate -> LateUpdate -> OnDestroy.", "confidence": 0.9},
    {"topic": "godot_game", "fact": "Godot GDScript template: extends CharacterBody2D; @export var speed := 200.0; func _physics_process(delta): var velocity = Vector2.ZERO; velocity.x = Input.get_axis('ui_left', 'ui_right'); velocity.y = Input.get_axis('ui_up', 'ui_down'); velocity = velocity.normalized() * speed; move_and_slide(). Signals: signal health_changed(new_health); func take_damage(amount): health -= amount; health_changed.emit(health).", "confidence": 0.9},
    {"topic": "arduino_firmware", "fact": "Arduino template: #include <DHT.h>; #define DHTPIN 2; DHT dht(DHTPIN, DHT22); void setup() { Serial.begin(9600); dht.begin(); } void loop() { float temp = dht.readTemperature(); float humidity = dht.readHumidity(); if (!isnan(temp)) { Serial.print('Temp: '); Serial.print(temp); Serial.println('C'); } delay(2000); }. Libraries via Arduino IDE or PlatformIO.", "confidence": 0.9},
    {"topic": "rpi_project", "fact": "Raspberry Pi Python template: import RPi.GPIO as GPIO; import time; LED_PIN = 18; GPIO.setmode(GPIO.BCM); GPIO.setup(LED_PIN, GPIO.OUT); pwm = GPIO.PWM(LED_PIN, 1000); pwm.start(0); try: while True: for dc in range(0, 101, 5): pwm.ChangeDutyCycle(dc); time.sleep(0.05); for dc in range(100, -1, -5): pwm.ChangeDutyCycle(dc); time.sleep(0.05); finally: pwm.stop(); GPIO.cleanup().", "confidence": 0.9},
]

# ═══════════════════════════════════════════════════
# COLLECTION 4 — DATABASE PATTERNS (20 entries)
# ═══════════════════════════════════════════════════

DATABASE_PATTERNS = [
    {"topic": "db_normalization", "fact": "Database normalization: 1NF (atomic values, no repeating groups), 2NF (no partial dependencies on composite key), 3NF (no transitive dependencies), BCNF (every determinant is a candidate key). Denormalize for read performance: materialized views, computed columns, pre-joined tables. Trade-off: normalized for writes, denormalized for reads.", "confidence": 0.95},
    {"topic": "db_indexing", "fact": "Database indexing: B-tree (default, range queries, ORDER BY), Hash (exact equality only), GIN (arrays, JSONB, full-text in PostgreSQL), GiST (geometric, range types). Composite index: CREATE INDEX idx ON orders(user_id, created_at DESC). Partial: WHERE status = 'active'. Covering: INCLUDE (columns) to avoid table lookups. EXPLAIN ANALYZE to verify index usage.", "confidence": 0.95},
    {"topic": "db_migration", "fact": "Database migrations: Alembic (Python/SQLAlchemy): alembic revision --autogenerate -m 'add users'; alembic upgrade head. Prisma: npx prisma migrate dev --name add_users. Django: python manage.py makemigrations; python manage.py migrate. Flyway (Java): V1__Create_users.sql. Always: backup before migrate, test on staging, handle rollbacks.", "confidence": 0.95},
    {"topic": "db_postgres_patterns", "fact": "PostgreSQL patterns: UPSERT — INSERT INTO users (email, name) VALUES ($1, $2) ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name. Pub/Sub: LISTEN channel; NOTIFY channel, 'payload'. Advisory locks: pg_advisory_lock(key). Partitioning: CREATE TABLE orders (...) PARTITION BY RANGE (created_at). Connection pooling: PgBouncer in transaction mode.", "confidence": 0.95},
    {"topic": "db_redis_patterns", "fact": "Redis patterns: caching — SET key value EX 3600; GET key. Rate limiting: INCR user:ip:count; EXPIRE user:ip:count 60. Session store: HSET session:id field value. Pub/Sub: PUBLISH channel msg; SUBSCRIBE channel. Sorted sets for leaderboards: ZADD leaderboard score member; ZREVRANGE leaderboard 0 9. Streams for event log: XADD stream * field value.", "confidence": 0.95},
    {"topic": "db_mongodb_patterns", "fact": "MongoDB patterns: Document model — embed related data that's read together. References for large/shared data. Aggregation pipeline: db.orders.aggregate([{$match:{status:'completed'}}, {$group:{_id:'$userId', total:{$sum:'$amount'}}}, {$sort:{total:-1}}, {$limit:10}]). Indexes: createIndex({userId:1, createdAt:-1}). Change Streams for real-time: db.collection.watch().", "confidence": 0.95},
    {"topic": "db_query_optimization", "fact": "Query optimization: EXPLAIN ANALYZE shows actual execution plan and timing. Common fixes: add missing indexes, avoid SELECT *, use LIMIT, replace subqueries with JOINs or CTEs, use EXISTS instead of IN for large sets, avoid functions on indexed columns (WHERE YEAR(date) = 2024 → WHERE date >= '2024-01-01'). Connection pooling reduces connection overhead.", "confidence": 0.95},
    {"topic": "db_cte_patterns", "fact": "CTE patterns: recursive CTE for hierarchies — WITH RECURSIVE tree AS (SELECT id, parent_id, name, 1 as depth FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.parent_id, c.name, t.depth + 1 FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT * FROM tree ORDER BY depth, name. Materialized CTE in PostgreSQL 12+: WITH cte AS MATERIALIZED (...).", "confidence": 0.95},
    {"topic": "db_window_functions", "fact": "Window functions: ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salary DESC) as rank — assigns sequential numbers. RANK() leaves gaps for ties, DENSE_RANK() doesn't. LAG(salary, 1) OVER(ORDER BY hire_date) — previous row value. Running total: SUM(amount) OVER(ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW). NTILE(4) for quartiles.", "confidence": 0.95},
    {"topic": "db_nosql_patterns", "fact": "NoSQL patterns: Key-Value (Redis, DynamoDB) — session store, cache, counters. Document (MongoDB, Firestore) — flexible schema, nested data. Column-Family (Cassandra, ScyllaDB) — time-series, write-heavy. Graph (Neo4j, Neptune) — relationships, social networks. Choose based on: access patterns, consistency needs, scale requirements. CAP theorem: pick 2 of consistency, availability, partition tolerance.", "confidence": 0.95},
    {"topic": "db_sharding", "fact": "Database sharding: horizontal partitioning across servers. Shard key selection is critical — high cardinality, even distribution, query alignment. Strategies: range-based (date ranges), hash-based (hash(user_id) % N), directory-based (lookup table). Cross-shard queries are expensive. Vitess for MySQL sharding, Citus for PostgreSQL. Alternative: read replicas for read scaling.", "confidence": 0.9},
    {"topic": "db_backup_strategies", "fact": "Database backup strategies: Full backup (complete copy, large but simple), Incremental (changes since last backup, fast but complex restore), WAL archiving (PostgreSQL continuous archiving, point-in-time recovery). pg_dump for logical backup, pg_basebackup for physical. Test restores regularly. 3-2-1 rule: 3 copies, 2 media types, 1 offsite.", "confidence": 0.9},
    {"topic": "db_connection_pooling", "fact": "Connection pooling: PgBouncer (PostgreSQL, lightweight, transaction/session/statement modes), HikariCP (Java, fastest JVM pool), SQLAlchemy pool (Python, create_engine(pool_size=20, max_overflow=10)). Pool sizing: connections = (cpu_cores * 2) + disk_spindles. Too many connections: context switching overhead. Too few: request queuing.", "confidence": 0.9},
    {"topic": "db_elasticsearch", "fact": "Elasticsearch patterns: index with mappings (text for full-text, keyword for exact match). Query DSL: { 'query': { 'bool': { 'must': [{ 'match': { 'title': 'search term' } }], 'filter': [{ 'range': { 'date': { 'gte': '2024-01-01' } } }] } } }. Aggregations for analytics. Bulk API for indexing. Index aliases for zero-downtime reindexing.", "confidence": 0.9},
    {"topic": "db_time_series", "fact": "Time-series databases: TimescaleDB (PostgreSQL extension) — hypertables with automatic partitioning by time. InfluxDB — line protocol, Flux query language. Retention policies for automatic data expiry. Continuous aggregates for pre-computed rollups. Compression for old data. Common: IoT sensors, metrics, financial data, logs.", "confidence": 0.9},
    {"topic": "db_graph_patterns", "fact": "Graph database patterns (Neo4j): CREATE (alice:Person {name:'Alice'})-[:KNOWS]->(bob:Person {name:'Bob'}). MATCH (p:Person)-[:KNOWS*1..3]->(friend) WHERE p.name = 'Alice' RETURN friend.name — finds friends up to 3 hops. PageRank, community detection, shortest path algorithms built-in. Use cases: social networks, recommendation engines, fraud detection, knowledge graphs.", "confidence": 0.9},
    {"topic": "db_sqlite_patterns", "fact": "SQLite patterns: WAL mode for concurrent reads — PRAGMA journal_mode=WAL. ATTACH DATABASE 'other.db' AS other for cross-database queries. JSON1 extension: json_extract(col, '$.key'), json_each(). FTS5 full-text: CREATE VIRTUAL TABLE docs USING fts5(title, body); SELECT * FROM docs WHERE docs MATCH 'search term'. Perfect for: embedded apps, mobile, CLI tools, testing.", "confidence": 0.9},
    {"topic": "db_data_modeling", "fact": "Data modeling: Entity-Relationship Diagram (ERD) — entities (tables), attributes (columns), relationships (1:1, 1:N, M:N). Junction/bridge table for M:N. Surrogate keys (auto-increment/UUID) vs natural keys. Soft deletes (deleted_at timestamp) vs hard deletes. Audit columns: created_at, updated_at, created_by. Version column for optimistic locking.", "confidence": 0.95},
    {"topic": "db_transactions", "fact": "Database transactions: ACID — Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent safety), Durability (survives crash). Isolation levels: READ UNCOMMITTED (dirty reads), READ COMMITTED (no dirty reads), REPEATABLE READ (no non-repeatable reads), SERIALIZABLE (no phantom reads). PostgreSQL default: READ COMMITTED. Use SELECT FOR UPDATE for row-level locks.", "confidence": 0.95},
    {"topic": "db_replication", "fact": "Database replication: Primary-Replica (master-slave) — writes to primary, reads from replicas. Synchronous (strong consistency, higher latency) vs asynchronous (eventual consistency, lower latency). Streaming replication in PostgreSQL. Multi-primary for write scaling (conflict resolution needed). Logical replication for selective table sync. Failover: automatic with tools like Patroni.", "confidence": 0.9},
]

# ═══════════════════════════════════════════════════
# COLLECTION 5 — DEVOPS PATTERNS (20 entries)
# ═══════════════════════════════════════════════════

DEVOPS_PATTERNS = [
    {"topic": "dockerfile_best", "fact": "Dockerfile best practices: multi-stage builds — FROM node:20 AS build; WORKDIR /app; COPY package*.json .; RUN npm ci; COPY . .; RUN npm run build; FROM node:20-slim; COPY --from=build /app/dist ./dist; CMD ['node', 'dist/index.js']. Use .dockerignore. Pin versions. Non-root user: RUN adduser --disabled-password app; USER app. Layer caching: COPY package.json before source.", "confidence": 0.95},
    {"topic": "docker_compose", "fact": "Docker Compose patterns: services: app: build: .; ports: ['3000:3000']; environment: DATABASE_URL: postgres://user:pass@db:5432/app; depends_on: db: condition: service_healthy; db: image: postgres:16; healthcheck: test: ['CMD-SHELL', 'pg_isready']; interval: 5s; volumes: [pgdata:/var/lib/postgresql/data]; redis: image: redis:7-alpine; volumes: pgdata:.", "confidence": 0.95},
    {"topic": "github_actions", "fact": "GitHub Actions CI/CD: name: CI; on: push: branches: [main]; pull_request:; jobs: test: runs-on: ubuntu-latest; steps: - uses: actions/checkout@v4; - uses: actions/setup-node@v4; with: node-version: 20; - run: npm ci; - run: npm test; deploy: needs: test; if: github.ref == 'refs/heads/main'; runs-on: ubuntu-latest; steps: - uses: actions/checkout@v4; - run: docker build -t app .; - run: docker push registry/app:latest.", "confidence": 0.95},
    {"topic": "github_actions_matrix", "fact": "GitHub Actions matrix strategy: strategy: matrix: node-version: [18, 20, 22]; os: [ubuntu-latest, macos-latest]; steps: - uses: actions/setup-node@v4; with: node-version: ${{ matrix.node-version }}. Caching: - uses: actions/cache@v4; with: path: ~/.npm; key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}.", "confidence": 0.95},
    {"topic": "k8s_helm", "fact": "Kubernetes Helm chart: Chart.yaml (name, version), values.yaml (configurable params), templates/ (deployment.yaml, service.yaml, ingress.yaml). values.yaml: replicaCount: 3; image: repository: myapp; tag: latest; service: type: ClusterIP; port: 80. Template: replicas: {{ .Values.replicaCount }}. helm install myapp ./chart; helm upgrade myapp ./chart; helm rollback myapp 1.", "confidence": 0.9},
    {"topic": "k8s_manifests", "fact": "Kubernetes core manifests: Deployment (manages pods), Service (network endpoint), ConfigMap (config data), Secret (sensitive data), Ingress (HTTP routing), HPA (auto-scaling). kubectl apply -f deployment.yaml. kubectl get pods. kubectl logs pod-name. kubectl exec -it pod-name -- sh. kubectl rollout status/undo deployment/name. Namespace isolation: kubectl create namespace staging.", "confidence": 0.95},
    {"topic": "terraform_iac", "fact": "Terraform IaC: provider 'aws' { region = 'us-east-1' }; resource 'aws_instance' 'web' { ami = 'ami-xxx'; instance_type = 't3.micro'; tags = { Name = 'web-server' } }. terraform init/plan/apply/destroy. State: terraform.tfstate (store remotely in S3+DynamoDB). Modules: module 'vpc' { source = './modules/vpc' }. Variables: variable 'env' { default = 'dev' }.", "confidence": 0.9},
    {"topic": "nginx_config", "fact": "Nginx configuration: server { listen 80; server_name example.com; location / { proxy_pass http://app:3000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; } location /api { proxy_pass http://api:8000; } location /static { alias /var/www/static; expires 30d; } }. SSL: listen 443 ssl; ssl_certificate /etc/ssl/cert.pem; ssl_certificate_key /etc/ssl/key.pem.", "confidence": 0.95},
    {"topic": "monitoring_stack", "fact": "Monitoring stack: Prometheus (metrics collection, PromQL queries, alerting rules) + Grafana (dashboards, visualization). Application metrics: prometheus_client (Python), prom-client (Node). Key metrics: RED (Rate, Errors, Duration) for services, USE (Utilization, Saturation, Errors) for resources. Alert example: rate(http_requests_total{status=~'5..'}[5m]) > 0.05.", "confidence": 0.9},
    {"topic": "logging_stack", "fact": "Logging stack: ELK (Elasticsearch + Logstash + Kibana) or Loki + Grafana. Structured logging: JSON format with timestamp, level, message, request_id, user_id. Python: structlog or loguru. Node: pino or winston. Correlation IDs across services. Log levels: DEBUG < INFO < WARNING < ERROR < CRITICAL. Don't log PII or secrets. Retention policy: 30 days hot, 90 days warm, 1 year cold.", "confidence": 0.9},
    {"topic": "ci_cd_pipeline", "fact": "CI/CD pipeline stages: 1) Lint (eslint, ruff, clippy), 2) Type check (tsc, mypy), 3) Unit tests, 4) Build (docker build, npm build), 5) Integration tests, 6) Security scan (Snyk, Trivy), 7) Deploy to staging, 8) E2E tests on staging, 9) Deploy to production (blue-green or canary), 10) Smoke tests. Rollback: automatic on health check failure.", "confidence": 0.95},
    {"topic": "gitops", "fact": "GitOps: ArgoCD or Flux watches a Git repo for Kubernetes manifests. Changes to manifests trigger automatic deployment. Pull-based model (cluster pulls from Git, no CI pushing to cluster). Environments: separate branches or directories (envs/staging/, envs/production/). Sealed Secrets for encrypted secrets in Git. Kustomize for environment-specific overlays.", "confidence": 0.9},
    {"topic": "container_security", "fact": "Container security: scan images with Trivy/Snyk (trivy image myapp:latest). Use minimal base images (alpine, distroless). Non-root user in Dockerfile. Read-only filesystem: docker run --read-only. No secrets in images — use runtime env vars or secret managers. Network policies in Kubernetes. Pod Security Standards: restricted profile. Supply chain: sign images with cosign.", "confidence": 0.9},
    {"topic": "load_balancing", "fact": "Load balancing strategies: Round Robin (equal distribution), Least Connections (fewest active), IP Hash (sticky sessions), Weighted (proportional to capacity). AWS ALB for HTTP/HTTPS with path-based routing. HAProxy for TCP/HTTP with health checks. Kubernetes Service (kube-proxy iptables/IPVS). Rate limiting: token bucket algorithm. Circuit breaker: open/half-open/closed states.", "confidence": 0.9},
    {"topic": "secrets_management", "fact": "Secrets management: HashiCorp Vault (dynamic secrets, encryption as a service, PKI). AWS Secrets Manager/Parameter Store. Azure Key Vault. GCP Secret Manager. Kubernetes: external-secrets-operator syncs from Vault/AWS to K8s Secrets. Never commit secrets to Git. .env files for local dev only (add to .gitignore). Rotate secrets regularly. Least privilege access.", "confidence": 0.9},
    {"topic": "zero_downtime_deploy", "fact": "Zero-downtime deployment: Blue-Green (two identical environments, switch traffic). Rolling update (gradually replace instances). Canary (route small % to new version, monitor, then full rollout). Kubernetes: maxSurge: 1, maxUnavailable: 0. Database migrations must be backward-compatible. Feature flags for gradual rollout. Health check endpoint: /healthz.", "confidence": 0.9},
    {"topic": "makefile_patterns", "fact": "Makefile patterns: .PHONY: test lint build deploy; test: pytest -v --cov=src; lint: ruff check src && mypy src; build: docker build -t app:$(VERSION) .; deploy: kubectl apply -f k8s/; dev: docker compose up -d && uvicorn main:app --reload; clean: find . -name '__pycache__' -exec rm -rf {} +; help: @grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = \":.*?## \"}; {printf \"%-15s %s\\n\", $$1, $$2}'.", "confidence": 0.95},
    {"topic": "pre_commit_hooks", "fact": "Pre-commit hooks: .pre-commit-config.yaml — repos: - repo: https://github.com/pre-commit/pre-commit-hooks; hooks: - id: trailing-whitespace; - id: check-yaml; - repo: https://github.com/astral-sh/ruff-pre-commit; hooks: - id: ruff; - id: ruff-format. Install: pre-commit install. Run all: pre-commit run --all-files. Prevents bad commits from entering the repo.", "confidence": 0.95},
    {"topic": "env_management", "fact": "Environment management: .env for local development (never commit). .env.example with placeholder values (commit this). dotenv library loads .env into process.env / os.environ. Docker: env_file: .env in compose. Kubernetes: ConfigMap for non-sensitive, Secret for sensitive. 12-Factor App: store config in environment. Validate required vars at startup.", "confidence": 0.95},
    {"topic": "git_workflow", "fact": "Git workflow: trunk-based development — short-lived feature branches, merge to main frequently. Branch naming: feature/add-auth, fix/login-bug, chore/update-deps. Conventional commits: feat:, fix:, chore:, docs:, refactor:, test:. Squash merge for clean history. Semantic versioning: MAJOR.MINOR.PATCH. Changelog: auto-generate from conventional commits.", "confidence": 0.95},
]

# ═══════════════════════════════════════════════════
# COLLECTION 6 — UI PATTERNS (15 entries)
# ═══════════════════════════════════════════════════

UI_PATTERNS = [
    {"topic": "responsive_layout", "fact": "Responsive layout: CSS Grid for 2D layouts — display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem. Flexbox for 1D — display: flex; flex-wrap: wrap; gap: 1rem. Container queries: @container (min-width: 400px) { .card { flex-direction: row } }. Mobile-first: start with mobile styles, add min-width breakpoints.", "confidence": 0.95},
    {"topic": "form_patterns", "fact": "Form patterns (React): react-hook-form — const { register, handleSubmit, formState: { errors } } = useForm<FormData>({ resolver: zodResolver(schema) }). Zod schema: z.object({ email: z.string().email(), password: z.string().min(8) }). Controlled with debounced validation. Show inline errors below fields. Disable submit while invalid or loading.", "confidence": 0.95},
    {"topic": "modal_dialog", "fact": "Modal/Dialog pattern: React — const [open, setOpen] = useState(false); <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button>Open</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Title</DialogTitle></DialogHeader>Body<DialogFooter><Button onClick={() => setOpen(false)}>Close</Button></DialogFooter></DialogContent></Dialog>. Focus trap, ESC to close, click outside to close.", "confidence": 0.95},
    {"topic": "data_table", "fact": "Data table pattern: TanStack Table (React) — const table = useReactTable({ data, columns, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), getFilteredRowModel: getFilteredRowModel() }). Features: sorting, filtering, pagination, row selection, column resizing. Virtualize large datasets with react-virtual.", "confidence": 0.95},
    {"topic": "toast_notification", "fact": "Toast notification pattern: react-hot-toast — toast.success('Saved!'); toast.error('Failed'); toast.promise(saveData(), { loading: 'Saving...', success: 'Saved!', error: 'Error' }). Sonner alternative: toast('Event created'). Position: top-right. Auto-dismiss: 3-5 seconds. Action button for undo. Stack multiple toasts. Accessible: role='alert' aria-live='assertive'.", "confidence": 0.95},
    {"topic": "infinite_scroll", "fact": "Infinite scroll pattern: IntersectionObserver — const observer = new IntersectionObserver((entries) => { if (entries[0].isIntersecting) loadMore(); }, { threshold: 0.1 }); observer.observe(sentinelRef.current). React Query: useInfiniteQuery({ queryKey: ['items'], queryFn: ({pageParam}) => fetchItems(pageParam), getNextPageParam: (lastPage) => lastPage.nextCursor }).", "confidence": 0.95},
    {"topic": "dark_mode", "fact": "Dark mode pattern: Tailwind — class='dark:bg-gray-900 dark:text-white'. Toggle: document.documentElement.classList.toggle('dark'). System preference: @media (prefers-color-scheme: dark). CSS variables: :root { --bg: white; --text: black } .dark { --bg: #1a1a2e; --text: #e0e0e0 }. Store preference in localStorage. next-themes for Next.js.", "confidence": 0.95},
    {"topic": "sidebar_nav", "fact": "Sidebar navigation pattern: collapsible — const [collapsed, setCollapsed] = useState(false). Width transition: transition-all duration-300. Icon-only when collapsed. Tooltips on icons in collapsed state. Active link highlight. Nested menus with accordion. Mobile: overlay drawer with backdrop. Store collapsed state in localStorage. shadcn/ui Sidebar component.", "confidence": 0.95},
    {"topic": "skeleton_loading", "fact": "Skeleton loading pattern: show placeholder shapes while content loads. CSS: .skeleton { background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%); background-size: 200% 100%; animation: shimmer 1.5s infinite; }. React: {loading ? <Skeleton className='h-4 w-[200px]' /> : <Text>{data.title}</Text>}. Better UX than spinners for content-heavy pages.", "confidence": 0.95},
    {"topic": "drag_drop", "fact": "Drag and drop: @dnd-kit (React) — DndContext, SortableContext, useSortable, useDraggable, useDroppable. Sensors: PointerSensor, KeyboardSensor. DragOverlay for custom drag preview. Collision detection: closestCenter, closestCorners, rectIntersection. react-beautiful-dnd (legacy but simpler API). HTML5: draggable='true', ondragstart, ondragover, ondrop.", "confidence": 0.9},
    {"topic": "auth_ui", "fact": "Auth UI pattern: Login form with email/password, social OAuth buttons (Google, GitHub), magic link option. Registration with password strength meter. Protected routes: redirect to /login if unauthenticated. JWT: store in httpOnly cookie (not localStorage). Refresh token rotation. Session display in header with avatar dropdown (profile, settings, logout).", "confidence": 0.95},
    {"topic": "dashboard_layout", "fact": "Dashboard layout: sidebar (nav) + header (breadcrumbs, user menu) + main content. Stat cards row: KPI metrics with trend indicators (up/down arrows, sparklines). Charts: Recharts (React), Chart.js, or D3.js. Data tables with search/filter/sort. Date range picker for filtering. Responsive: sidebar collapses on mobile. Grid layout: grid-cols-1 md:grid-cols-2 lg:grid-cols-4.", "confidence": 0.95},
    {"topic": "command_palette", "fact": "Command palette (Cmd+K): cmdk library — <CommandDialog open={open} onOpenChange={setOpen}><CommandInput placeholder='Type a command...' /><CommandList><CommandGroup heading='Navigation'><CommandItem onSelect={() => router.push('/dashboard')}>Dashboard</CommandItem></CommandGroup></CommandList></CommandDialog>. Global keyboard shortcut. Fuzzy search. Recent items. kbar as alternative.", "confidence": 0.9},
    {"topic": "file_upload", "fact": "File upload UI: react-dropzone — const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop, accept: { 'image/*': ['.png','.jpg'] }, maxSize: 5*1024*1024 }). Preview thumbnails before upload. Progress bar during upload. Drag-and-drop zone with dashed border. Multiple file support. Chunked upload for large files. presigned S3 URLs for direct upload.", "confidence": 0.95},
    {"topic": "animation_patterns", "fact": "Animation patterns: Framer Motion (React) — <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} exit={{opacity:0}} transition={{duration:0.3}}>. AnimatePresence for mount/unmount animations. Layout animations for reorder. CSS: @keyframes fadeIn { from { opacity: 0 } to { opacity: 1 } }. Prefer transform/opacity for 60fps (GPU-accelerated). prefers-reduced-motion media query.", "confidence": 0.95},
]

# ═══════════════════════════════════════════════════
# COLLECTION 7 — TESTING PATTERNS (15 entries)
# ═══════════════════════════════════════════════════

TESTING_PATTERNS = [
    {"topic": "pytest_patterns", "fact": "Pytest patterns: def test_create_user(): user = create_user('Alice'); assert user.name == 'Alice'; assert user.id is not None. Fixtures: @pytest.fixture; def db(): engine = create_engine('sqlite://'); yield Session(engine); engine.dispose(). Parametrize: @pytest.mark.parametrize('input,expected', [(1,1),(2,4),(3,9)]). Mocking: from unittest.mock import patch, MagicMock; @patch('module.function').", "confidence": 0.95},
    {"topic": "jest_patterns", "fact": "Jest patterns: describe('UserService', () => { it('should create user', async () => { const user = await service.create({name: 'Alice'}); expect(user.name).toBe('Alice'); expect(user.id).toBeDefined(); }); }). Mocking: jest.mock('./db'); const mockFn = jest.fn().mockResolvedValue({id: 1}). beforeEach(() => { jest.clearAllMocks(); }). Snapshot: expect(component).toMatchSnapshot().", "confidence": 0.95},
    {"topic": "rtl_patterns", "fact": "React Testing Library: render(<LoginForm />); const emailInput = screen.getByLabelText('Email'); const submitBtn = screen.getByRole('button', {name: /submit/i}); await userEvent.type(emailInput, 'test@test.com'); await userEvent.click(submitBtn); expect(screen.getByText('Welcome')).toBeInTheDocument(). Test behavior, not implementation. findBy for async elements.", "confidence": 0.95},
    {"topic": "go_testing", "fact": "Go testing: func TestAdd(t *testing.T) { got := Add(2, 3); want := 5; if got != want { t.Errorf('Add(2,3) = %d; want %d', got, want) } }. Table-driven: tests := []struct{ a, b, want int }{{1,2,3},{0,0,0}}; for _, tc := range tests { t.Run(fmt.Sprintf('%d+%d', tc.a, tc.b), func(t *testing.T) { ... }) }. go test -v -cover -race. Benchmarks: func BenchmarkAdd(b *testing.B) { for i := 0; i < b.N; i++ { Add(1,2) } }.", "confidence": 0.95},
    {"topic": "rust_testing", "fact": "Rust testing: #[cfg(test)] mod tests { use super::*; #[test] fn test_add() { assert_eq!(add(2, 3), 5); } #[test] #[should_panic(expected = 'division by zero')] fn test_divide_zero() { divide(1, 0); } }. Integration tests in tests/ directory. cargo test -- --nocapture for println output. #[ignore] for slow tests. proptest for property-based testing.", "confidence": 0.95},
    {"topic": "e2e_playwright", "fact": "Playwright E2E: test('login flow', async ({ page }) => { await page.goto('/login'); await page.getByLabel('Email').fill('user@test.com'); await page.getByLabel('Password').fill('password123'); await page.getByRole('button', {name: 'Log in'}).click(); await expect(page.getByText('Dashboard')).toBeVisible(); }). npx playwright test --headed. Codegen: npx playwright codegen localhost:3000. Trace viewer for debugging.", "confidence": 0.95},
    {"topic": "cypress_patterns", "fact": "Cypress E2E: describe('Login', () => { it('should login with valid credentials', () => { cy.visit('/login'); cy.get('[data-testid=email]').type('user@test.com'); cy.get('[data-testid=password]').type('pass123'); cy.get('button[type=submit]').click(); cy.url().should('include', '/dashboard'); cy.contains('Welcome').should('be.visible'); }); }). Custom commands: Cypress.Commands.add('login', (email, password) => { ... }).", "confidence": 0.95},
    {"topic": "mock_patterns", "fact": "Mocking patterns: MSW (Mock Service Worker) — server.use(http.get('/api/users', () => HttpResponse.json([{id:1,name:'Alice'}]))); test('displays users', async () => { render(<UserList />); expect(await screen.findByText('Alice')).toBeInTheDocument(); }). Python: @patch('requests.get') def test_fetch(mock_get): mock_get.return_value.json.return_value = {'name': 'Alice'}.", "confidence": 0.95},
    {"topic": "tdd_workflow", "fact": "TDD workflow: 1) RED — write a failing test for the desired behavior, 2) GREEN — write minimum code to make the test pass, 3) REFACTOR — improve code while keeping tests green. Benefits: design emerges from usage (test-first), regression safety, documentation through tests. Test pyramid: many unit tests (fast, isolated), fewer integration tests (service boundaries), few E2E tests (slow, brittle).", "confidence": 0.95},
    {"topic": "api_testing", "fact": "API testing: httpx (Python) — async with httpx.AsyncClient(app=app, base_url='http://test') as client: response = await client.post('/api/users', json={'name': 'Alice'}); assert response.status_code == 201; assert response.json()['name'] == 'Alice'. Supertest (Node): const res = await request(app).post('/api/users').send({name: 'Alice'}).expect(201).", "confidence": 0.95},
    {"topic": "fixture_patterns", "fact": "Fixture patterns: factory functions — def make_user(**overrides): defaults = {'name': 'Alice', 'email': 'alice@test.com', 'active': True}; defaults.update(overrides); return User(**defaults). Database fixtures: transaction rollback after each test. FactoryBot (Ruby): create(:user, name: 'Bob'). Faker for realistic data: faker.internet.email(). Seed data for consistent test runs.", "confidence": 0.95},
    {"topic": "load_testing", "fact": "Load testing: k6 — import http from 'k6/http'; export default function() { const res = http.get('http://localhost:3000/api/users'); check(res, { 'status is 200': (r) => r.status === 200, 'response time < 200ms': (r) => r.timings.duration < 200 }); }. Options: vus: 100, duration: '30s'. Locust (Python): class UserBehavior(HttpUser): @task def get_users(self): self.client.get('/api/users').", "confidence": 0.9},
    {"topic": "snapshot_testing", "fact": "Snapshot testing: Jest — expect(render(<Button variant='primary'>Click</Button>)).toMatchSnapshot(). Updates: jest --updateSnapshot. Inline snapshots: expect(result).toMatchInlineSnapshot(`'expected output'`). Python: syrupy — def test_output(snapshot): assert generate_report() == snapshot. Good for: serialized output, component rendering, API responses. Bad for: frequently changing output.", "confidence": 0.9},
    {"topic": "contract_testing", "fact": "Contract testing: Pact — consumer defines expected interactions, provider verifies it can fulfill them. Consumer test: const interaction = { uponReceiving: 'a request for users', withRequest: { method: 'GET', path: '/api/users' }, willRespondWith: { status: 200, body: [{ id: like(1), name: like('Alice') }] } }. Provider verification: verifier.verifyProvider({providerBaseUrl, pactUrls}). Prevents integration failures.", "confidence": 0.9},
    {"topic": "mutation_testing", "fact": "Mutation testing: automatically modifies code (mutants) and checks if tests catch the changes. If a mutant survives, tests are insufficient. Tools: mutmut (Python) — mutmut run; mutmut results; mutmut show <id>. Stryker (JS/TS) — npx stryker run. Mutations: replace operators (+→-), flip booleans, remove statements, change return values. Metric: mutation score = killed/total.", "confidence": 0.9},
]

# ═══════════════════════════════════════════════════
# COLLECTION 8 — CLOUD PATTERNS (20 entries)
# ═══════════════════════════════════════════════════

CLOUD_PATTERNS = [
    {"topic": "aws_s3", "fact": "AWS S3 patterns: boto3 — s3 = boto3.client('s3'); s3.upload_file('local.txt', 'bucket', 'key.txt'); s3.download_file('bucket', 'key.txt', 'local.txt'). Presigned URLs: url = s3.generate_presigned_url('get_object', Params={'Bucket': b, 'Key': k}, ExpiresIn=3600). Static website hosting. Lifecycle rules for archival to Glacier. Cross-region replication. Server-side encryption: AES-256 or KMS.", "confidence": 0.9},
    {"topic": "aws_lambda", "fact": "AWS Lambda: handler receives event and context. Cold start: ~100ms (Python), ~500ms (Java). Layers for shared dependencies. Environment variables for config. VPC access for RDS/ElastiCache. API Gateway integration for HTTP. SQS/SNS/EventBridge for event triggers. Provisioned concurrency to avoid cold starts. Max: 15 min timeout, 10GB memory, 250MB package.", "confidence": 0.9},
    {"topic": "aws_ecs", "fact": "AWS ECS: Task Definition (container config: image, CPU, memory, ports, env vars). Service (desired count, load balancer, auto-scaling). Fargate (serverless, no EC2 management) vs EC2 launch type. ECR for Docker registry. Service discovery with Cloud Map. Blue-green deployment with CodeDeploy. Secrets from Secrets Manager or Parameter Store.", "confidence": 0.9},
    {"topic": "aws_rds", "fact": "AWS RDS: managed PostgreSQL/MySQL/Aurora. Multi-AZ for HA (automatic failover). Read replicas for scaling reads. Automated backups with point-in-time recovery. Performance Insights for query analysis. Parameter groups for tuning. Aurora Serverless v2 scales 0-128 ACUs. RDS Proxy for connection pooling. IAM auth for tokenless access.", "confidence": 0.9},
    {"topic": "gcp_cloud_run", "fact": "GCP Cloud Run: container-based serverless — gcloud run deploy myservice --image gcr.io/project/image --platform managed --allow-unauthenticated. Auto-scales 0-1000 instances. Max 3600s timeout. Concurrency: up to 1000 requests per instance. Cloud Build for CI: cloudbuild.yaml — steps: - name: gcr.io/cloud-builders/docker; args: [build, -t, image, .]; images: [image].", "confidence": 0.9},
    {"topic": "gcp_firestore", "fact": "GCP Firestore: NoSQL document database. Collections > Documents > Fields. Real-time listeners: onSnapshot(). Queries: db.collection('users').where('age', '>', 18).orderBy('name').limit(10).get(). Security rules: match /users/{userId} { allow read, write: if request.auth.uid == userId }. Offline persistence built-in. Composite indexes for multi-field queries.", "confidence": 0.9},
    {"topic": "azure_functions", "fact": "Azure Functions: function.json defines trigger and bindings. HTTP trigger: def main(req: func.HttpRequest) -> func.HttpResponse: name = req.params.get('name'); return func.HttpResponse(f'Hello {name}'). Timer trigger: @app.schedule(schedule='0 */5 * * * *', arg_name='timer'). Durable Functions for orchestration. Application Insights for monitoring.", "confidence": 0.9},
    {"topic": "azure_cosmosdb", "fact": "Azure Cosmos DB: globally distributed, multi-model database. APIs: SQL (document), MongoDB, Cassandra, Gremlin (graph), Table. Consistency levels: Strong, Bounded Staleness, Session (default), Consistent Prefix, Eventual. Partition key selection critical for performance. RU/s (Request Units) for throughput. Change feed for event-driven architectures.", "confidence": 0.9},
    {"topic": "cdn_patterns", "fact": "CDN patterns: CloudFront (AWS), Cloud CDN (GCP), Azure CDN, Cloudflare. Cache static assets (JS, CSS, images) at edge. Cache-Control headers: public, max-age=31536000, immutable (for hashed filenames). Invalidation: cloudfront create-invalidation --paths '/*'. Origin failover. Custom error pages. Lambda@Edge/Cloudflare Workers for edge compute.", "confidence": 0.9},
    {"topic": "serverless_patterns", "fact": "Serverless patterns: API composition — Lambda behind API Gateway. Fan-out: SNS topic triggers multiple Lambdas. Async processing: SQS queue + Lambda consumer. Scheduled: EventBridge rule + Lambda. Streaming: Kinesis/DynamoDB Streams + Lambda. Step Functions for orchestration (state machine). Cold start mitigation: provisioned concurrency, keep-warm pings, smaller packages.", "confidence": 0.9},
    {"topic": "cloud_networking", "fact": "Cloud networking: VPC (Virtual Private Cloud) with public/private subnets. NAT Gateway for private subnet internet access. Security Groups (instance-level firewall, stateful) vs NACLs (subnet-level, stateless). VPN/Direct Connect for hybrid. Transit Gateway for multi-VPC. Private endpoints for AWS services (no internet traffic). DNS: Route 53 with health checks.", "confidence": 0.9},
    {"topic": "cloud_iam", "fact": "Cloud IAM: principle of least privilege. AWS: IAM users/roles/policies. Roles for services (EC2, Lambda assume role). Policy: {Effect: Allow, Action: ['s3:GetObject'], Resource: 'arn:aws:s3:::bucket/*'}. GCP: service accounts, IAM roles. Azure: RBAC, managed identities. Cross-account access with trust policies. MFA for human users. Rotate access keys regularly.", "confidence": 0.9},
    {"topic": "cloud_storage_tiers", "fact": "Cloud storage tiers: AWS S3 Standard (frequent access), S3-IA (infrequent, lower cost), S3 Glacier (archive, minutes-hours retrieval), S3 Glacier Deep Archive (cheapest, 12-hour retrieval). GCP: Standard, Nearline (30-day min), Coldline (90-day), Archive (365-day). Lifecycle policies auto-transition objects. Intelligent Tiering auto-optimizes.", "confidence": 0.9},
    {"topic": "cloud_messaging", "fact": "Cloud messaging: AWS SQS (queue, exactly-once with FIFO, dead letter queue), SNS (pub/sub, fan-out to SQS/Lambda/HTTP), EventBridge (event bus with rules and targets). GCP: Pub/Sub (at-least-once, ordering keys). Azure: Service Bus (queues and topics). Patterns: request-response, fire-and-forget, competing consumers, priority queues.", "confidence": 0.9},
    {"topic": "cloud_cost", "fact": "Cloud cost optimization: right-size instances (use CloudWatch/Monitoring metrics). Reserved Instances/Savings Plans for stable workloads (up to 72% savings). Spot/Preemptible for fault-tolerant workloads (up to 90% savings). Auto-scaling to match demand. S3 lifecycle policies. Delete unused resources (EBS volumes, old snapshots, idle load balancers). AWS Cost Explorer + budgets.", "confidence": 0.9},
    {"topic": "cloud_disaster_recovery", "fact": "Disaster recovery: RPO (Recovery Point Objective) — max data loss tolerance. RTO (Recovery Time Objective) — max downtime. Strategies: Backup & Restore (hours RTO, cheapest), Pilot Light (minutes RTO, minimal infra), Warm Standby (seconds-minutes, scaled-down copy), Multi-Site Active-Active (near-zero, most expensive). Cross-region replication for databases and storage.", "confidence": 0.9},
    {"topic": "cloud_observability", "fact": "Cloud observability: three pillars — Metrics (Prometheus/CloudWatch/Datadog), Logs (CloudWatch Logs/Loki/ELK), Traces (Jaeger/X-Ray/Datadog APM). OpenTelemetry for vendor-neutral instrumentation. Service mesh (Istio) for automatic tracing. SLIs/SLOs/error budgets. Dashboards: Grafana. Alerting: PagerDuty/OpsGenie integration. Runbooks for incident response.", "confidence": 0.9},
    {"topic": "cloud_databases", "fact": "Cloud database services: AWS RDS/Aurora (relational), DynamoDB (key-value/document), ElastiCache (Redis/Memcached), Neptune (graph), Redshift (data warehouse). GCP Cloud SQL, Spanner (global relational), BigQuery (analytics). Azure SQL, Cosmos DB. Managed = automated backups, patching, HA. Serverless options: Aurora Serverless, DynamoDB on-demand, Cosmos DB serverless.", "confidence": 0.9},
    {"topic": "vercel_deploy", "fact": "Vercel deployment: connect GitHub repo, auto-deploys on push. Framework auto-detection (Next.js, React, Vue, Svelte). Preview deployments for PRs. Environment variables in project settings. Edge Functions for low-latency compute. Edge Config for feature flags. Cron jobs: vercel.json { cron: [{ path: '/api/cron', schedule: '0 * * * *' }] }. Analytics and Web Vitals built-in.", "confidence": 0.9},
    {"topic": "netlify_deploy", "fact": "Netlify deployment: connect Git repo, auto-builds on push. Build command and publish directory in netlify.toml. Serverless functions in netlify/functions/. Forms: <form name='contact' netlify>. Identity for auth. Split testing (A/B). Edge functions for low-latency. Build plugins for custom build steps. Branch deploys for staging environments.", "confidence": 0.9},
]


def load_all_collections(engine: KnowledgeEngine) -> dict:
    """Load all 8 knowledge collections into the KnowledgeEngine.

    Returns a summary dict with counts per collection.
    """
    collections = {
        "programming_languages": PROGRAMMING_LANGUAGES,
        "framework_patterns": FRAMEWORK_PATTERNS,
        "app_templates": APP_TEMPLATES,
        "database_patterns": DATABASE_PATTERNS,
        "devops_patterns": DEVOPS_PATTERNS,
        "ui_patterns": UI_PATTERNS,
        "testing_patterns": TESTING_PATTERNS,
        "cloud_patterns": CLOUD_PATTERNS,
    }

    summary = {}
    for name, entries in collections.items():
        count = 0
        for entry in entries:
            engine.add_fact(
                topic=entry["topic"],
                fact=entry["fact"],
                confidence=entry.get("confidence", 0.9),
            )
            count += 1
        summary[name] = count

    return summary


def get_collection(name: str) -> list:
    """Get a specific knowledge collection by name."""
    collections = {
        "programming_languages": PROGRAMMING_LANGUAGES,
        "framework_patterns": FRAMEWORK_PATTERNS,
        "app_templates": APP_TEMPLATES,
        "database_patterns": DATABASE_PATTERNS,
        "devops_patterns": DEVOPS_PATTERNS,
        "ui_patterns": UI_PATTERNS,
        "testing_patterns": TESTING_PATTERNS,
        "cloud_patterns": CLOUD_PATTERNS,
    }
    return collections.get(name, [])


def list_collections() -> dict:
    """List all available collections with entry counts."""
    return {
        "programming_languages": len(PROGRAMMING_LANGUAGES),
        "framework_patterns": len(FRAMEWORK_PATTERNS),
        "app_templates": len(APP_TEMPLATES),
        "database_patterns": len(DATABASE_PATTERNS),
        "devops_patterns": len(DEVOPS_PATTERNS),
        "ui_patterns": len(UI_PATTERNS),
        "testing_patterns": len(TESTING_PATTERNS),
        "cloud_patterns": len(CLOUD_PATTERNS),
    }


def search_collections(query: str, limit: int = 10) -> list:
    """Search across all collections for matching entries."""
    query_lower = query.lower()
    results = []
    all_collections = {
        "programming_languages": PROGRAMMING_LANGUAGES,
        "framework_patterns": FRAMEWORK_PATTERNS,
        "app_templates": APP_TEMPLATES,
        "database_patterns": DATABASE_PATTERNS,
        "devops_patterns": DEVOPS_PATTERNS,
        "ui_patterns": UI_PATTERNS,
        "testing_patterns": TESTING_PATTERNS,
        "cloud_patterns": CLOUD_PATTERNS,
    }
    for coll_name, entries in all_collections.items():
        for entry in entries:
            if query_lower in entry["fact"].lower() or query_lower in entry["topic"].lower():
                results.append({
                    "collection": coll_name,
                    "topic": entry["topic"],
                    "fact": entry["fact"],
                    "confidence": entry["confidence"],
                })
    results.sort(key=lambda x: x["confidence"], reverse=True)
    return results[:limit]
