#!/usr/bin/env python3
"""
NICTO Super Training v3.0 - Stage 1: Supervised Fine-Tuning
Auto-generated by train_super_v3.py
"""

import json, os, torch, sys
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"

# ─── Config ─────────────────────────────────────────────────────────────────
BASE_MODEL = "deepseek-ai/DeepSeek-V4"
DATA_PATH = "C:/Users/BYU/Desktop/NIKTO/nicto_neural/training_data/super_v3_chatml.jsonl"
OUTPUT_DIR = "C:/Users/BYU/Desktop/NIKTO/nicto_neural/nicto_outputs/models/nicto_super_v3"
MAX_SEQ_LENGTH = 8192
LORA_R = 32
LORA_ALPHA = 64
BATCH_SIZE = 2
GRAD_ACCUM = 8
LR = 0.0002
EPOCHS = 3

# ─── Load Data ──────────────────────────────────────────────────────────────
print(f"Loading training data from {DATA_PATH}...")
with open(DATA_PATH, "r", encoding="utf-8") as f:
    raw_data = [json.loads(line) for line in f if line.strip()]
print(f"Loaded {len(raw_data)} training examples.")

# ─── Unsloth Setup ─────────────────────────────────────────────────────────
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template, train_on_responses_only
from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer

dtype = torch.bfloat16 if is_bfloat16_supported() else torch.float16

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=dtype,
    load_in_4bit=True,
)

tokenizer = get_chat_template(tokenizer, chat_template="chatml")

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_alpha=LORA_ALPHA,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
    use_rslora=True,
    loftq_config=None,
)

print(f"Model loaded: {BASE_MODEL}")
print(f"Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad)}")

# ─── Format Dataset ────────────────────────────────────────────────────────
def format_func(examples):
    texts = []
    for msg_list in examples["messages"]:
        text = ""
        for msg in msg_list:
            role = msg["role"]
            content = msg["content"]
            text += f"<|im_start|>{role}\n{content}<|im_end|>\n"
        text += "<|im_start|>assistant\n"
        texts.append(text)
    return {"text": texts}

dataset = Dataset.from_list(raw_data)
dataset = dataset.map(format_func, batched=True)
print(f"Dataset: {len(dataset)} examples")

# ─── Train ──────────────────────────────────────────────────────────────────
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=4,
    packing=False,
    args=TrainingArguments(
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRAD_ACCUM,
        warmup_steps=20,
        num_train_epochs=EPOCHS,
        learning_rate=LR,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        output_dir=OUTPUT_DIR,
        report_to="none",
        save_strategy="epoch",
        eval_strategy="no",
        save_total_limit=3,
        ddp_find_unused_parameters=False,
        dataloader_num_workers=4,
    ),
)

trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)

print("\n=== STARTING SFT TRAINING ===")
trainer_stats = trainer.train()
final_loss = trainer_stats.training_loss

print(f"\n=== SFT COMPLETE ===")
print(f"  Model: {BASE_MODEL}")
print(f"  Examples: {len(raw_data)}")
print(f"  Epochs: {EPOCHS}")
print(f"  Final loss: {final_loss:.4f}")

# Save LoRA adapters
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"LoRA adapters saved to {OUTPUT_DIR}")

# Save merged
merge_path = OUTPUT_DIR + "_merged"
model.save_pretrained_merged(merge_path, tokenizer)
print(f"Merged model saved to {merge_path}")

# Export GGUF
gguf_path = OUTPUT_DIR + "_gguf"
model.save_pretrained_gguf(gguf_path, tokenizer, quantization_method="q4_k_m")
print(f"GGUF model saved to {gguf_path}")
